#!/usr/bin/env node

import { Command } from 'commander';
import * as fs from 'fs-extra';
import * as path from 'path';
import * as readline from 'readline';

// Read version from centralized location
const getVersion = (): string => {
  try {
    const versionPath = path.join(__dirname, '..', 'version.json');
    const { version } = JSON.parse(fs.readFileSync(versionPath, 'utf8'));
    return version;
  } catch (error) {
    return '1.0.6'; // fallback version
  }
};

interface DataType {
  mongoose: string;
  typescript: string;
}

interface ProjectTemplates {
  [key: string]: string;
}

interface Colors {
  green: (text: string) => string;
  blue: (text: string) => string;
  yellow: (text: string) => string;
  red: (text: string) => string;
  cyan: (text: string) => string;
  bold: (text: string) => string;
  dim: (text: string) => string;
}

const program = new Command();

// Console colors without chalk
const colors: Colors = {
  green: (text: string) => `\x1b[32m${text}\x1b[0m`,
  blue: (text: string) => `\x1b[34m${text}\x1b[0m`,
  yellow: (text: string) => `\x1b[33m${text}\x1b[0m`,
  red: (text: string) => `\x1b[31m${text}\x1b[0m`,
  cyan: (text: string) => `\x1b[36m${text}\x1b[0m`,
  bold: (text: string) => `\x1b[1m${text}\x1b[0m`,
  dim: (text: string) => `\x1b[2m${text}\x1b[0m`
};

// Available Mongoose data types with TypeScript equivalents
const availableDataTypes: DataType[] = [
  { mongoose: 'String', typescript: 'string' },
  { mongoose: 'Number', typescript: 'number' },
  { mongoose: 'Date', typescript: 'Date' },
  { mongoose: 'Boolean', typescript: 'boolean' },
  { mongoose: 'ObjectId', typescript: 'Types.ObjectId' },
  { mongoose: 'Array', typescript: 'Array' },
  { mongoose: 'Mixed', typescript: 'any' },
  { mongoose: 'Decimal128', typescript: 'Types.Decimal128' },
  { mongoose: 'Map', typescript: 'Map<string, any>' },
  { mongoose: 'Schema', typescript: 'Schema' }
];

// Available enum types for generation
const enumTypes: string[] = ['string', 'number'];

// Helper function to create readline interface
const createReadlineInterface = (): readline.Interface => {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
};

// Helper function to ask question
const askQuestion = (rl: readline.Interface, question: string): Promise<string> => {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
};

// Helper function to capitalize first letter
const capitalize = (str: string): string => {
  return str.charAt(0).toUpperCase() + str.slice(1);
};

// Helper function to convert to camelCase
const toCamelCase = (str: string): string => {
  return str.charAt(0).toLowerCase() + str.slice(1);
};

// Helper function to convert to kebab-case
const toKebabCase = (str: string): string => {
  return str.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
};

// Helper function to read existing schemas
const readExistingSchemas = async (projectPath: string): Promise<string[]> => {
  const schemasPath = path.join(projectPath, 'src', 'schemas');
  if (!await fs.pathExists(schemasPath)) {
    return [];
  }
  
  const files = await fs.readdir(schemasPath);
  return files
    .filter(file => file.endsWith('.ts'))
    .map(file => file.replace('.ts', ''));
};

// Project templates as a constant object
const projectTemplates: ProjectTemplates = {
  'package.json': JSON.stringify({
    name: "{{PROJECT_NAME}}",
    version: getVersion(),
    description: "Bun API project with Express and MongoDB",
    main: "dist/server.js",
    scripts: {
      build: "tsc",
      start: "node dist/server.js",
      dev: "bun --watch src/server.ts",
      "dev:ts": "ts-node src/server.ts",
      test: "echo \"Error: no test specified\" && exit 1"
    },
    dependencies: {
      "express": "^4.18.2",
      "mongoose": "^8.0.0",
      "dotenv": "^16.3.1",
      "cors": "^2.8.5",
      "helmet": "^7.1.0",
      "bcryptjs": "^2.4.3",
      "jsonwebtoken": "^9.0.2",
      "express-rate-limit": "^7.1.5",
      "joi": "^17.11.0",
      "swagger-jsdoc": "^6.2.8",
      "swagger-ui-express": "^5.0.0"
    },
    devDependencies: {
      "typescript": "^5.3.2",
      "@types/express": "^4.17.21",
      "@types/node": "^20.10.0",
      "@types/cors": "^2.8.17",
      "@types/bcryptjs": "^2.4.6",
      "@types/jsonwebtoken": "^9.0.5",
      "@types/swagger-jsdoc": "^6.0.4",
      "@types/swagger-ui-express": "^4.1.6",
      "ts-node": "^10.9.1",
      "nodemon": "^3.0.2"
    },
    keywords: ["bun", "express", "mongodb", "api", "typescript"],
    author: "mynenikoteshwarrao",
    license: "MIT",
    disclaimer: `Generated by Koti CLI v${getVersion()} - Development version. Code provided as-is without warranty. Review before production use.`
  }, null, 2),

  'tsconfig.json': JSON.stringify({
    compilerOptions: {
      target: "ES2020",
      module: "CommonJS",
      lib: ["ES2020"],
      outDir: "./dist",
      rootDir: "./src",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      declaration: true,
      sourceMap: true,
      removeComments: false,
      noImplicitAny: true,
      strictNullChecks: true,
      moduleResolution: "node",
      allowSyntheticDefaultImports: true,
      experimentalDecorators: true,
      emitDecoratorMetadata: true
    },
    include: [
      "src/**/*"
    ],
    exclude: [
      "node_modules",
      "dist"
    ]
  }, null, 2),

  'README.md': `# {{PROJECT_NAME}}

A modern TypeScript API built with Bun, Express.js, and MongoDB.

## ⚠️ Development Disclaimer

**This project was generated using Koti CLI (Development Version 1.0.3)**

This is an initial development release and may contain errors, bugs, or security vulnerabilities. Please:
- Review all generated code before using in production
- Test thoroughly in development environments
- Update dependencies to latest versions
- Implement proper security measures for production use
- Use at your own discretion and risk

Generated code is provided "as-is" without warranty of any kind.

## 🚀 Features

- **TypeScript**: Full type safety and modern JavaScript features
- **Bun Runtime**: Lightning-fast JavaScript runtime
- **Express.js**: Minimal and flexible web framework
- **MongoDB**: NoSQL database with Mongoose ODM
- **Authentication**: JWT-based authentication system
- **Security**: Helmet, CORS, rate limiting
- **Error Handling**: Centralized error handling
- **Validation**: Joi request validation and sanitization
- **API Documentation**: Swagger/OpenAPI 3.0 documentation
- **Environment Config**: Environment-based configuration

## 📋 Prerequisites

- [Bun](https://bun.sh/) installed
- [MongoDB](https://www.mongodb.com/) installed and running
- Node.js 16+ (for development tools)
- TypeScript knowledge recommended

## 🛠️ Installation

1. **Clone the repository**
   \`\`\`bash
   git clone <repository-url>
   cd {{PROJECT_NAME}}
   \`\`\`

2. **Install dependencies**
   \`\`\`bash
   bun install
   \`\`\`

3. **Set up environment variables**
   \`\`\`bash
   cp .env.example .env
   \`\`\`
   
   Edit \`.env\` file with your configuration:
   \`\`\`env
   NODE_ENV=development
   PORT=8000
   MONGODB_URI=mongodb://localhost:27017/{{PROJECT_NAME}}
   JWT_SECRET=your-super-secret-jwt-key
   \`\`\`

4. **Start MongoDB**
   \`\`\`bash
   # On macOS with Homebrew
   brew services start mongodb-community
   
   # On Linux
   sudo systemctl start mongod
   \`\`\`

## 🚀 Usage

### Development

\`\`\`bash
# Development with Bun (recommended)
bun run dev

# Development with TypeScript compilation
npm run dev:ts

# Build TypeScript
npm run build

# Production
npm start
\`\`\`

### API Documentation

- **Swagger UI**: http://localhost:8000/api-docs
- **Health Check**: http://localhost:8000/health
- **API Status**: http://localhost:8000/api/status

### Default Endpoints

- \`GET /health\` - Health check
- \`GET /api/\` - API welcome message
- \`GET /api/status\` - API status information
- \`GET /api-docs\` - Interactive API documentation

### Authentication Endpoints

- \`POST /api/auth/register\` - Register new user
- \`POST /api/auth/login\` - User login
- \`GET /api/auth/me\` - Get current user profile

## 📁 Project Structure

\`\`\`
{{PROJECT_NAME}}/
├── src/
│   ├── config/
│   │   ├── database.ts         # MongoDB connection
│   │   └── swagger.ts          # Swagger configuration
│   ├── controllers/
│   │   ├── authController.ts   # Authentication logic
│   │   └── index.ts           # Controller exports
│   ├── middleware/
│   │   ├── auth.ts            # JWT authentication
│   │   ├── errorHandler.ts    # Error handling
│   │   ├── rateLimit.ts       # Rate limiting
│   │   └── validation.ts      # Joi validation
│   ├── models/
│   │   ├── User.ts            # User model
│   │   └── index.ts           # Model exports
│   ├── routes/
│   │   ├── auth.ts            # Auth routes
│   │   ├── index.ts           # Main routes
│   │   └── api.ts             # API routes
│   ├── types/
│   │   └── api.ts             # TypeScript definitions
│   ├── utils/
│   │   ├── AppError.ts        # Custom error class
│   │   ├── logger.ts          # Logging utility
│   │   └── responseHelper.ts  # Response helpers
│   └── server.ts              # Main server file
├── dist/                      # Compiled JavaScript
├── .env                       # Environment variables
├── .gitignore                 # Git ignore rules
├── package.json               # Dependencies
├── tsconfig.json              # TypeScript config
└── README.md                  # This file
\`\`\`

## 🔧 Development

### Adding New Features

Use the Koti CLI to generate new components:

\`\`\`bash
# Create new model
koti create:model Product

# Create new controller
koti create:controller Product

# Create new service
koti create:service Email

# Create new middleware
koti create:middleware Logger

# Create new enum
koti create:enum Status
\`\`\`

### TypeScript Features

- **Full Type Safety**: All code is written in TypeScript
- **Interface Definitions**: Clear contracts for all data structures
- **Enum Support**: Type-safe enumerations
- **Generic Types**: Reusable type definitions
- **Decorators**: Support for experimental decorators

## 🛡️ Security Features

- **JWT Authentication**: Secure token-based authentication
- **Password Hashing**: bcrypt for secure password storage
- **Rate Limiting**: Protection against brute force attacks
- **CORS**: Cross-origin resource sharing configuration
- **Helmet**: Security headers middleware
- **Input Validation**: Joi validation for all inputs

## 📊 Monitoring & Logging

- **Health Checks**: Built-in health check endpoints
- **Request Logging**: Detailed request/response logging
- **Error Tracking**: Comprehensive error logging
- **Performance Monitoring**: Request timing and metrics

## 🧪 Testing

\`\`\`bash
# Run tests (when implemented)
npm test

# Type checking
npx tsc --noEmit

# Linting (when configured)
npm run lint
\`\`\`

## 🚀 Deployment

### Production Build

\`\`\`bash
# Build for production
npm run build

# Start production server
npm start
\`\`\`

### Environment Variables

Set the following environment variables for production:

- \`NODE_ENV=production\`
- \`PORT=8000\`
- \`MONGODB_URI=your-production-mongodb-uri\`
- \`JWT_SECRET=your-secure-jwt-secret\`

## 📄 License

MIT License - see LICENSE file for details.

## 🤝 Contributing

1. Fork the repository
2. Create a feature branch
3. Make your changes
4. Add tests if applicable
5. Submit a pull request

## 📞 Support

For support, please open an issue in the repository or contact the maintainer.

---

Generated with ❤️ by [Koti CLI](https://www.npmjs.com/package/koti)
`
};

// Generate TypeScript Model
const generateTypeScriptModel = (modelName: string, fields: any[]): string => {
  const capitalizedName = capitalize(modelName);
  const fieldsCode = fields.map(field => {
    const options = [];
    if (field.required) options.push('required: true');
    if (field.unique) options.push('unique: true');
    if (field.default) options.push(`default: ${field.type === 'String' ? `'${field.default}'` : field.default}`);
    
    const optionsString = options.length > 0 ? `, { ${options.join(', ')} }` : '';
    return `  ${field.name}: { type: ${field.type}${optionsString} }`;
  }).join(',\n');

  return `import { Schema, model, Document, Types } from 'mongoose';

export interface I${capitalizedName} extends Document {
${fields.map(field => {
  const tsType = field.type === 'ObjectId' ? 'Types.ObjectId' : 
                 field.type === 'String' ? 'string' :
                 field.type === 'Number' ? 'number' :
                 field.type === 'Boolean' ? 'boolean' :
                 field.type === 'Date' ? 'Date' :
                 field.type === 'Array' ? 'any[]' : 'any';
  return `  ${field.name}: ${tsType};`;
}).join('\n')}
}

const ${capitalizedName}Schema = new Schema<I${capitalizedName}>({
${fieldsCode}
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

export const ${capitalizedName} = model<I${capitalizedName}>('${capitalizedName}', ${capitalizedName}Schema);
export default ${capitalizedName};
`;
};

// Generate TypeScript Enum
const generateTypeScriptEnum = (enumName: string, enumType: 'string' | 'number', values: { key: string; value: string | number }[]): string => {
  const capitalizedName = capitalize(enumName);
  
  const enumValues = values.map(({ key, value }) => {
    if (enumType === 'string') {
      return `  ${key} = '${value}'`;
    }
    return `  ${key} = ${value}`;
  }).join(',\n');

  return `export enum ${capitalizedName} {
${enumValues}
}

export default ${capitalizedName};
`;
};

// Generate TypeScript Controller
const generateTypeScriptController = (controllerName: string): string => {
  const capitalizedName = capitalize(controllerName);
  const camelCaseName = toCamelCase(controllerName);
  
  return `import { Request, Response, NextFunction } from 'express';
import { ApiResponse, PaginatedResponse, AuthenticatedRequest } from '../types/api';
import { AppError } from '../utils/AppError';

export class ${capitalizedName}Controller {
  /**
   * Get all ${controllerName}s with pagination
   * @route GET /api/${toKebabCase(controllerName)}
   */
  public async getAll(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const page = parseInt(req.query.page as string) || 1;
      const limit = parseInt(req.query.limit as string) || 10;
      const skip = (page - 1) * limit;

      // TODO: Implement actual data fetching logic
      const data = []; // Replace with actual data fetching
      const total = 0; // Replace with actual count

      const response: PaginatedResponse = {
        success: true,
        message: '${capitalizedName}s retrieved successfully',
        data,
        pagination: {
          page,
          limit,
          total,
          totalPages: Math.ceil(total / limit),
          hasNext: page < Math.ceil(total / limit),
          hasPrev: page > 1
        }
      };

      res.status(200).json(response);
    } catch (error) {
      next(new AppError(\`Error fetching ${controllerName}s\`, 500));
    }
  }

  /**
   * Get single ${controllerName} by ID
   * @route GET /api/${toKebabCase(controllerName)}/:id
   */
  public async getById(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { id } = req.params;

      // TODO: Implement actual data fetching logic
      const data = null; // Replace with actual data fetching

      if (!data) {
        return next(new AppError('${capitalizedName} not found', 404));
      }

      const response: ApiResponse = {
        success: true,
        message: '${capitalizedName} retrieved successfully',
        data
      };

      res.status(200).json(response);
    } catch (error) {
      next(new AppError(\`Error fetching ${controllerName}\`, 500));
    }
  }

  /**
   * Create new ${controllerName}
   * @route POST /api/${toKebabCase(controllerName)}
   */
  public async create(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
    try {
      const { body } = req;

      // TODO: Implement validation and creation logic
      const data = body; // Replace with actual creation logic

      const response: ApiResponse = {
        success: true,
        message: '${capitalizedName} created successfully',
        data
      };

      res.status(201).json(response);
    } catch (error) {
      next(new AppError(\`Error creating ${controllerName}\`, 400));
    }
  }

  /**
   * Update ${controllerName} by ID
   * @route PUT /api/${toKebabCase(controllerName)}/:id
   */
  public async update(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
    try {
      const { id } = req.params;
      const { body } = req;

      // TODO: Implement actual update logic
      const data = body; // Replace with actual update logic

      const response: ApiResponse = {
        success: true,
        message: '${capitalizedName} updated successfully',
        data
      };

      res.status(200).json(response);
    } catch (error) {
      next(new AppError(\`Error updating ${controllerName}\`, 400));
    }
  }

  /**
   * Delete ${controllerName} by ID
   * @route DELETE /api/${toKebabCase(controllerName)}/:id
   */
  public async delete(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
    try {
      const { id } = req.params;

      // TODO: Implement actual deletion logic

      const response: ApiResponse = {
        success: true,
        message: '${capitalizedName} deleted successfully'
      };

      res.status(200).json(response);
    } catch (error) {
      next(new AppError(\`Error deleting ${controllerName}\`, 400));
    }
  }
}

export default new ${capitalizedName}Controller();
`;
};

// Generate TypeScript Service
const generateTypeScriptService = (serviceName: string): string => {
  const capitalizedName = capitalize(serviceName);
  
  return `import { AppError } from '../utils/AppError';

export class ${capitalizedName}Service {
  /**
   * Service method example
   * @param data - Input data
   * @returns Promise<any>
   */
  public async performOperation(data: any): Promise<any> {
    try {
      // TODO: Implement service logic here
      return data;
    } catch (error) {
      throw new AppError(\`${capitalizedName} service error: \${error}\`, 500);
    }
  }

  /**
   * Validation method example
   * @param data - Data to validate
   * @returns boolean
   */
  public validateData(data: any): boolean {
    // TODO: Implement validation logic
    return data !== null && data !== undefined;
  }

  /**
   * Process data method example
   * @param rawData - Raw data to process
   * @returns Processed data
   */
  public processData(rawData: any): any {
    // TODO: Implement data processing logic
    return rawData;
  }
}

export default new ${capitalizedName}Service();
`;
};

// Generate TypeScript Middleware
const generateTypeScriptMiddleware = (middlewareName: string): string => {
  const camelCaseName = toCamelCase(middlewareName);
  
  return `import { Request, Response, NextFunction } from 'express';
import { AppError } from '../utils/AppError';

/**
 * ${capitalize(middlewareName)} middleware
 * @param req - Express request object
 * @param res - Express response object
 * @param next - Express next function
 */
export const ${camelCaseName} = (req: Request, res: Response, next: NextFunction): void => {
  try {
    // TODO: Implement middleware logic here
    console.log(\`${capitalize(middlewareName)} middleware executed for \${req.method} \${req.path}\`);
    
    // Example: Check some condition
    const isValid = true; // Replace with actual validation logic
    
    if (!isValid) {
      return next(new AppError('${capitalize(middlewareName)} validation failed', 400));
    }
    
    next();
  } catch (error) {
    next(new AppError(\`${capitalize(middlewareName)} middleware error\`, 500));
  }
};

export default ${camelCaseName};
`;
};

// Generate CRUD Controller
const generateCRUDController = (modelName: string, fields: any[]): string => {
  const capitalizedName = capitalize(modelName);
  const camelCaseName = modelName.toLowerCase();
  
  return `import { Request, Response, NextFunction } from 'express';
import { ApiResponse, PaginatedResponse, AuthenticatedRequest } from '../types/api';
import { AppError } from '../utils/AppError';
import ${capitalizedName}Service from '../services/${camelCaseName}Service';

export class ${capitalizedName}Controller {
  /**
   * Get all ${capitalizedName}s with pagination
   * @route GET /api/${camelCaseName}
   */
  public async getAll(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const page = parseInt(req.query.page as string) || 1;
      const limit = parseInt(req.query.limit as string) || parseInt(process.env.DEFAULT_PAGE_LIMIT || '10');
      const search = req.query.search as string;
      const sortBy = req.query.sortBy as string || 'createdAt';
      const sortOrder = req.query.sortOrder as 'asc' | 'desc' || 'desc';

      const result = await ${capitalizedName}Service.getAll({
        page,
        limit,
        search,
        sortBy,
        sortOrder
      });

      const response: PaginatedResponse = {
        success: true,
        message: '${capitalizedName}s retrieved successfully',
        data: result.data,
        pagination: result.pagination
      };

      res.status(200).json(response);
    } catch (error) {
      next(new AppError(\`Error fetching ${capitalizedName}s\`, 500));
    }
  }

  /**
   * Get single ${capitalizedName} by ID
   * @route GET /api/${camelCaseName}/:id
   */
  public async getById(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { id } = req.params;
      const ${camelCaseName} = await ${capitalizedName}Service.getById(id);

      if (!${camelCaseName}) {
        return next(new AppError('${capitalizedName} not found', 404));
      }

      const response: ApiResponse = {
        success: true,
        message: '${capitalizedName} retrieved successfully',
        data: ${camelCaseName}
      };

      res.status(200).json(response);
    } catch (error) {
      next(new AppError(\`Error fetching ${capitalizedName}\`, 500));
    }
  }

  /**
   * Create new ${capitalizedName}
   * @route POST /api/${camelCaseName}
   */
  public async create(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
    try {
      const ${camelCaseName} = await ${capitalizedName}Service.create(req.body);

      const response: ApiResponse = {
        success: true,
        message: '${capitalizedName} created successfully',
        data: ${camelCaseName}
      };

      res.status(201).json(response);
    } catch (error) {
      next(new AppError(\`Error creating ${capitalizedName}\`, 400));
    }
  }

  /**
   * Update ${capitalizedName} by ID
   * @route PUT /api/${camelCaseName}/:id
   */
  public async update(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
    try {
      const { id } = req.params;
      const ${camelCaseName} = await ${capitalizedName}Service.update(id, req.body);

      if (!${camelCaseName}) {
        return next(new AppError('${capitalizedName} not found', 404));
      }

      const response: ApiResponse = {
        success: true,
        message: '${capitalizedName} updated successfully',
        data: ${camelCaseName}
      };

      res.status(200).json(response);
    } catch (error) {
      next(new AppError(\`Error updating ${capitalizedName}\`, 400));
    }
  }

  /**
   * Delete ${capitalizedName} by ID
   * @route DELETE /api/${camelCaseName}/:id
   */
  public async delete(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
    try {
      const { id } = req.params;
      const deleted = await ${capitalizedName}Service.delete(id);

      if (!deleted) {
        return next(new AppError('${capitalizedName} not found', 404));
      }

      const response: ApiResponse = {
        success: true,
        message: '${capitalizedName} deleted successfully',
        data: null
      };

      res.status(200).json(response);
    } catch (error) {
      next(new AppError(\`Error deleting ${capitalizedName}\`, 500));
    }
  }
}

export default new ${capitalizedName}Controller();`;
};

// Generate CRUD Service
const generateCRUDService = (modelName: string, fields: any[]): string => {
  const capitalizedName = capitalize(modelName);
  const camelCaseName = modelName.toLowerCase();
  
  return `import { AppError } from '../utils/AppError';
import ${capitalizedName} from '../models/${capitalizedName}';
import { PaginationResult, QueryOptions } from '../types/api';

export class ${capitalizedName}Service {
  /**
   * Get all ${capitalizedName}s with pagination and search
   */
  public async getAll(options: QueryOptions): Promise<{ data: any[]; pagination: PaginationResult }> {
    try {
      const { page = 1, limit = 10, search, sortBy = 'createdAt', sortOrder = 'desc' } = options;
      const skip = (page - 1) * limit;

      // Build search query
      let query: any = {};
      if (search) {
        const searchFields = [${fields.filter(f => f.type === 'String').map(f => `'${f.name}'`).join(', ')}];
        if (searchFields.length > 0) {
          query.$or = searchFields.map(field => ({
            [field]: { $regex: search, $options: 'i' }
          }));
        }
      }

      // Execute queries
      const [data, total] = await Promise.all([
        ${capitalizedName}.find(query)
          .sort({ [sortBy]: sortOrder === 'asc' ? 1 : -1 })
          .skip(skip)
          .limit(limit)
          .lean(),
        ${capitalizedName}.countDocuments(query)
      ]);

      const totalPages = Math.ceil(total / limit);

      return {
        data,
        pagination: {
          page,
          limit,
          total,
          totalPages,
          hasNext: page < totalPages,
          hasPrev: page > 1
        }
      };
    } catch (error) {
      throw new AppError(\`Error fetching ${capitalizedName}s: \${error}\`, 500);
    }
  }

  /**
   * Get ${capitalizedName} by ID
   */
  public async getById(id: string): Promise<any> {
    try {
      const ${camelCaseName} = await ${capitalizedName}.findById(id).lean();
      return ${camelCaseName};
    } catch (error) {
      throw new AppError(\`Error fetching ${capitalizedName}: \${error}\`, 500);
    }
  }

  /**
   * Create new ${capitalizedName}
   */
  public async create(data: any): Promise<any> {
    try {
      const ${camelCaseName} = new ${capitalizedName}(data);
      await ${camelCaseName}.save();
      return ${camelCaseName}.toObject();
    } catch (error) {
      throw new AppError(\`Error creating ${capitalizedName}: \${error}\`, 400);
    }
  }

  /**
   * Update ${capitalizedName} by ID
   */
  public async update(id: string, data: any): Promise<any> {
    try {
      const ${camelCaseName} = await ${capitalizedName}.findByIdAndUpdate(
        id,
        { ...data, updatedAt: new Date() },
        { new: true, runValidators: true }
      ).lean();
      return ${camelCaseName};
    } catch (error) {
      throw new AppError(\`Error updating ${capitalizedName}: \${error}\`, 400);
    }
  }

  /**
   * Delete ${capitalizedName} by ID
   */
  public async delete(id: string): Promise<boolean> {
    try {
      const result = await ${capitalizedName}.findByIdAndDelete(id);
      return !!result;
    } catch (error) {
      throw new AppError(\`Error deleting ${capitalizedName}: \${error}\`, 500);
    }
  }
}

export default new ${capitalizedName}Service();`;
};

// Generate CRUD Routes
const generateCRUDRoutes = (modelName: string): string => {
  const capitalizedName = capitalize(modelName);
  const camelCaseName = modelName.toLowerCase();
  
  return `import { Router } from 'express';
import ${camelCaseName}Controller from '../controllers/${camelCaseName}Controller';
import { auth } from '../middleware/auth';

const router = Router();

/**
 * @swagger
 * components:
 *   schemas:
 *     ${capitalizedName}:
 *       type: object
 *       properties:
 *         id:
 *           type: string
 *           description: The auto-generated id of the ${camelCaseName}
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: Creation timestamp
 *         updatedAt:
 *           type: string
 *           format: date-time
 *           description: Last update timestamp
 */

/**
 * @swagger
 * /api/${camelCaseName}:
 *   get:
 *     summary: Get all ${camelCaseName}s with pagination
 *     tags: [${capitalizedName}]
 *     parameters:
 *       - in: query
 *         name: page
 *         schema:
 *           type: integer
 *           default: 1
 *         description: Page number
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *           default: 10
 *         description: Number of items per page
 *       - in: query
 *         name: search
 *         schema:
 *           type: string
 *         description: Search term
 *       - in: query
 *         name: sortBy
 *         schema:
 *           type: string
 *           default: createdAt
 *         description: Field to sort by
 *       - in: query
 *         name: sortOrder
 *         schema:
 *           type: string
 *           enum: [asc, desc]
 *           default: desc
 *         description: Sort order
 *     responses:
 *       200:
 *         description: List of ${camelCaseName}s
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/PaginatedResponse'
 */
router.get('/', ${camelCaseName}Controller.getAll);

/**
 * @swagger
 * /api/${camelCaseName}/{id}:
 *   get:
 *     summary: Get ${camelCaseName} by ID
 *     tags: [${capitalizedName}]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: ${capitalizedName} ID
 *     responses:
 *       200:
 *         description: ${capitalizedName} details
 *       404:
 *         description: ${capitalizedName} not found
 */
router.get('/:id', ${camelCaseName}Controller.getById);

/**
 * @swagger
 * /api/${camelCaseName}:
 *   post:
 *     summary: Create new ${camelCaseName}
 *     tags: [${capitalizedName}]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/${capitalizedName}'
 *     responses:
 *       201:
 *         description: ${capitalizedName} created successfully
 *       400:
 *         description: Validation error
 *       401:
 *         description: Unauthorized
 */
router.post('/', auth, ${camelCaseName}Controller.create);

/**
 * @swagger
 * /api/${camelCaseName}/{id}:
 *   put:
 *     summary: Update ${camelCaseName} by ID
 *     tags: [${capitalizedName}]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: ${capitalizedName} ID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/${capitalizedName}'
 *     responses:
 *       200:
 *         description: ${capitalizedName} updated successfully
 *       404:
 *         description: ${capitalizedName} not found
 *       401:
 *         description: Unauthorized
 */
router.put('/:id', auth, ${camelCaseName}Controller.update);

/**
 * @swagger
 * /api/${camelCaseName}/{id}:
 *   delete:
 *     summary: Delete ${camelCaseName} by ID
 *     tags: [${capitalizedName}]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: ${capitalizedName} ID
 *     responses:
 *       200:
 *         description: ${capitalizedName} deleted successfully
 *       404:
 *         description: ${capitalizedName} not found
 *       401:
 *         description: Unauthorized
 */
router.delete('/:id', auth, ${camelCaseName}Controller.delete);

export default router;`;
};

// Update main routes to register new route
const updateMainRoutes = async (modelName: string): Promise<void> => {
  const camelCaseName = modelName.toLowerCase();
  const routesIndexPath = path.join(process.cwd(), 'src', 'routes', 'index.ts');
  
  try {
    const currentContent = await fs.readFile(routesIndexPath, 'utf-8');
    
    // Add import statement
    const importStatement = `import ${camelCaseName}Routes from './${camelCaseName}';`;
    const routeUsage = `router.use('/${camelCaseName}', ${camelCaseName}Routes);`;
    
    // Check if already exists
    if (currentContent.includes(importStatement)) {
      return;
    }
    
    // Find the last import statement and add after it
    const lines = currentContent.split('\n');
    let lastImportIndex = -1;
    let routerUseIndex = -1;
    
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].startsWith('import') && lines[i].includes('from')) {
        lastImportIndex = i;
      }
      if (lines[i].includes('router.use') && lines[i].includes('Routes')) {
        routerUseIndex = i;
      }
    }
    
    // Insert import after last import
    if (lastImportIndex >= 0) {
      lines.splice(lastImportIndex + 1, 0, importStatement);
    }
    
    // Insert route usage after last router.use
    if (routerUseIndex >= 0) {
      lines.splice(routerUseIndex + 1, 0, routeUsage);
    }
    
    const updatedContent = lines.join('\n');
    await fs.writeFile(routesIndexPath, updatedContent);
    
  } catch (error) {
    console.log(colors.yellow('⚠️  Could not update routes/index.ts automatically'));
    console.log(colors.dim(`   Please add: router.use('/${camelCaseName}', ${camelCaseName}Routes);`));
  }
};

// Generate essential TypeScript files
const generateEssentialFiles = async (projectPath: string, projectName: string): Promise<void> => {
  const srcPath = path.join(projectPath, 'src');

  // Generate basic route files
  const indexRouteContent = `import { Router, Request, Response } from 'express';
import { ApiResponse } from '../types/api';

const router = Router();

/**
 * @swagger
 * /api/:
 *   get:
 *     summary: API welcome message
 *     tags: [Health]
 *     responses:
 *       200:
 *         description: Welcome message
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ApiResponse'
 */
router.get('/', (req: Request, res: Response) => {
  const response: ApiResponse = {
    success: true,
    message: 'Welcome to ${projectName} API',
    data: {
      version: getVersion(),
      description: 'TypeScript API built with Bun, Express, and MongoDB',
      documentation: '/api-docs'
    }
  };
  res.json(response);
});

/**
 * @swagger
 * /api/status:
 *   get:
 *     summary: API status information
 *     tags: [Health]
 *     responses:
 *       200:
 *         description: API status
 */
router.get('/status', (req: Request, res: Response) => {
  const response: ApiResponse = {
    success: true,
    message: 'API is running',
    data: {
      status: 'healthy',
      timestamp: new Date().toISOString(),
      uptime: process.uptime(),
      environment: process.env.NODE_ENV || 'development'
    }
  };
  res.json(response);
});

export default router;`;

  const authRouteContent = `import { Router } from 'express';
import authController from '../controllers/authController';
import { auth } from '../middleware/auth';

const router = Router();

/**
 * @swagger
 * /api/auth/register:
 *   post:
 *     summary: Register a new user
 *     tags: [Authentication]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - username
 *               - email
 *               - password
 *             properties:
 *               username:
 *                 type: string
 *               email:
 *                 type: string
 *               password:
 *                 type: string
 *     responses:
 *       201:
 *         description: User registered successfully
 *       400:
 *         description: Validation error
 */
router.post('/register', authController.register);

/**
 * @swagger
 * /api/auth/login:
 *   post:
 *     summary: Login user
 *     tags: [Authentication]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - email
 *               - password
 *             properties:
 *               email:
 *                 type: string
 *               password:
 *                 type: string
 *     responses:
 *       200:
 *         description: Login successful
 *       401:
 *         description: Invalid credentials
 */
router.post('/login', authController.login);

/**
 * @swagger
 * /api/auth/forgot-password:
 *   post:
 *     summary: Request password reset
 *     tags: [Authentication]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - email
 *             properties:
 *               email:
 *                 type: string
 *     responses:
 *       200:
 *         description: Password reset instructions sent
 *       404:
 *         description: User not found
 */
router.post('/forgot-password', authController.forgotPassword);

/**
 * @swagger
 * /api/auth/reset-password:
 *   post:
 *     summary: Reset password with token
 *     tags: [Authentication]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - token
 *               - newPassword
 *             properties:
 *               token:
 *                 type: string
 *               newPassword:
 *                 type: string
 *     responses:
 *       200:
 *         description: Password reset successful
 *       400:
 *         description: Invalid token or password
 */
router.post('/reset-password', authController.resetPassword);

/**
 * @swagger
 * /api/auth/refresh-token:
 *   post:
 *     summary: Refresh access token
 *     tags: [Authentication]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - refreshToken
 *             properties:
 *               refreshToken:
 *                 type: string
 *     responses:
 *       200:
 *         description: Token refreshed successfully
 *       401:
 *         description: Invalid refresh token
 */
router.post('/refresh-token', authController.refreshToken);

/**
 * @swagger
 * /api/auth/logout:
 *   post:
 *     summary: Logout user
 *     tags: [Authentication]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - refreshToken
 *             properties:
 *               refreshToken:
 *                 type: string
 *     responses:
 *       200:
 *         description: Logout successful
 */
router.post('/logout', authController.logout);

/**
 * @swagger
 * /api/auth/profile:
 *   get:
 *     summary: Get current user profile
 *     tags: [Authentication]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: User profile
 *       401:
 *         description: Unauthorized
 */
router.get('/profile', auth, authController.getProfile);

export default router;`;

  await fs.writeFile(path.join(srcPath, 'routes', 'index.ts'), indexRouteContent);
  await fs.writeFile(path.join(srcPath, 'routes', 'auth.ts'), authRouteContent);
  
  console.log(colors.green('✅ Created file: src/routes/index.ts'));
  console.log(colors.green('✅ Created file: src/routes/auth.ts'));

  // Generate enhanced auth controller with service layer
  const authControllerContent = `import { Request, Response, NextFunction } from 'express';
import { ApiResponse, AuthenticatedRequest, LoginRequest, RegisterRequest } from '../types/api';
import { AppError } from '../utils/AppError';
import * as authService from '../services/authService';

interface ForgotPasswordRequest {
  email: string;
}

interface ResetPasswordRequest {
  token: string;
  newPassword: string;
}

interface RefreshTokenRequest {
  refreshToken: string;
}

class AuthController {
  /**
   * Register new user
   * @route POST /api/auth/register
   */
  public async register(req: Request<{}, any, RegisterRequest>, res: Response, next: NextFunction): Promise<void> {
    try {
      const userData = req.body;
      const result = await authService.signup(userData);
      
      if (result.message) {
        const response: ApiResponse = {
          success: true,
          message: result.message,
          data: null
        };
        return res.status(200).json(response);
      }

      const response: ApiResponse = {
        success: true,
        message: 'User registered successfully',
        data: result.user
      };

      res.status(201).json(response);
    } catch (error: any) {
      next(new AppError(error.message || 'Registration failed', 400));
    }
  }

  /**
   * Login user
   * @route POST /api/auth/login
   */
  public async login(req: Request<{}, any, LoginRequest>, res: Response, next: NextFunction): Promise<void> {
    try {
      const { email, password } = req.body;
      const result = await authService.login(email, password);

      const response: ApiResponse = {
        success: true,
        message: 'Login successful',
        data: result
      };

      res.status(200).json(response);
    } catch (error: any) {
      next(new AppError(error.message || 'Invalid email or password', 401));
    }
  }

  /**
   * Forgot password
   * @route POST /api/auth/forgot-password
   */
  public async forgotPassword(req: Request<{}, any, ForgotPasswordRequest>, res: Response, next: NextFunction): Promise<void> {
    try {
      const { email } = req.body;
      const resetToken = await authService.forgotPassword(email);

      const response: ApiResponse = {
        success: true,
        message: 'Password reset instructions sent to your email',
        data: { resetToken: resetToken }
      };

      res.status(200).json(response);
    } catch (error: any) {
      next(new AppError(error.message || 'Failed to process forgot password request', 500));
    }
  }

  /**
   * Reset password
   * @route POST /api/auth/reset-password
   */
  public async resetPassword(req: Request<{}, any, ResetPasswordRequest>, res: Response, next: NextFunction): Promise<void> {
    try {
      const { token, newPassword } = req.body;
      await authService.resetPassword(token, newPassword);

      const response: ApiResponse = {
        success: true,
        message: 'Password has been reset successfully',
        data: null
      };

      res.status(200).json(response);
    } catch (error: any) {
      next(new AppError(error.message || 'Password reset failed', 400));
    }
  }

  /**
   * Refresh access token
   * @route POST /api/auth/refresh-token
   */
  public async refreshToken(req: Request<{}, any, RefreshTokenRequest>, res: Response, next: NextFunction): Promise<void> {
    try {
      const { refreshToken } = req.body;
      const newAccessToken = await authService.refreshAccessToken(refreshToken);

      const response: ApiResponse = {
        success: true,
        message: 'Token refreshed successfully',
        data: { accessToken: newAccessToken }
      };

      res.status(200).json(response);
    } catch (error: any) {
      next(new AppError(error.message || 'Token refresh failed', 401));
    }
  }

  /**
   * Logout user
   * @route POST /api/auth/logout
   */
  public async logout(req: Request<{}, any, RefreshTokenRequest>, res: Response, next: NextFunction): Promise<void> {
    try {
      const { refreshToken } = req.body;
      await authService.logout(refreshToken);

      const response: ApiResponse = {
        success: true,
        message: 'Logged out successfully',
        data: null
      };

      res.status(200).json(response);
    } catch (error: any) {
      next(new AppError(error.message || 'Logout failed', 500));
    }
  }

  /**
   * Get user profile
   * @route GET /api/auth/profile
   */
  public async getProfile(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
    try {
      const user = req.user;
      
      if (!user) {
        return next(new AppError('User not authenticated', 401));
      }

      const response: ApiResponse = {
        success: true,
        message: 'Profile retrieved successfully',
        data: user
      };

      res.status(200).json(response);
    } catch (error: any) {
      next(new AppError(error.message || 'Failed to get profile', 500));
    }
  }
}

export default new AuthController();`;

  const authMiddlewareContent = `import { Request, Response, NextFunction } from 'express';
import { AuthenticatedRequest } from '../types/api';
import { AppError } from '../utils/AppError';
import { verifyAccessToken } from '../utils/tokenUtils';

export const auth = async (req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> => {
  try {
    const authHeader = req.header('Authorization');
    
    if (!authHeader?.startsWith('Bearer ')) {
      return next(new AppError('Unauthorized: No token provided', 401));
    }

    const token = authHeader.split(' ')[1];
    const decoded = await verifyAccessToken(token);
    
    if (!decoded) {
      return next(new AppError('Unauthorized: Invalid token', 401));
    }

    req.user = decoded;
    next();
  } catch (error: any) {
    next(new AppError('Unauthorized: Invalid token', 401));
  }
};

export default auth;`;

  const errorHandlerContent = `import { Request, Response, NextFunction } from 'express';
import { AppError } from '../utils/AppError';
import { ErrorResponse } from '../types/api';

export const errorHandler = (
  error: Error | AppError,
  req: Request,
  res: Response,
  next: NextFunction
): void => {
  let statusCode = 500;
  let message = 'Internal server error';

  if (error instanceof AppError) {
    statusCode = error.statusCode;
    message = error.message;
  }

  const response: ErrorResponse = {
    success: false,
    message,
    error: error.name || 'UnknownError',
    statusCode,
    stack: process.env.NODE_ENV === 'development' ? error.stack : undefined
  };

  // Log error details in development
  if (process.env.NODE_ENV === 'development') {
    console.error('🚨 Error Details:', {
      message: error.message,
      stack: error.stack,
      url: req.url,
      method: req.method,
      body: req.body,
      params: req.params,
      query: req.query
    });
  } else {
    // Log only essential info in production
    console.error('Error:', error.message);
  }

  res.status(statusCode).json(response);
};

export const notFound = (req: Request, res: Response): void => {
  const response: ErrorResponse = {
    success: false,
    message: \`Not Found - [\${req.method}] \${req.url}\`,
    error: 'NotFound',
    statusCode: 404
  };

  res.status(404).json(response);
};

export default errorHandler;`;

  const envContent = `# Environment Configuration
NODE_ENV=development
PORT=8000

# Database
MONGODB_URI=mongodb://localhost:27017/${projectName}

# JWT Configuration
JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
JWT_REFRESH_SECRET=your-super-secret-jwt-refresh-key-change-this-in-production
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

# Frontend URL (for CORS)
FRONTEND_URL=http://localhost:5000

# API Configuration
API_URL=http://localhost:8000

# Pagination Configuration
DEFAULT_PAGE_LIMIT=10
MAX_PAGE_LIMIT=100`;

  // Generate auth service layer
  const authServiceContent = `import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import { Types } from 'mongoose';
import User from '../models/User';
import { generateAccessToken, generateRefreshToken, verifyRefreshToken } from '../utils/tokenUtils';
import { AppError } from '../utils/AppError';

export interface IUser {
  _id?: string;
  username: string;
  email: string;
  password?: string;
  createdAt?: Date;
  updatedAt?: Date;
}

export const login = async (email: string, password: string) => {
  const user = await User.findOne({ email }).lean();
  if (!user) {
    throw new AppError('Invalid email or password', 401);
  }

  const passwordMatches = await bcrypt.compare(password, user.password);
  if (!passwordMatches) {
    throw new AppError('Invalid email or password', 401);
  }

  const userId = (user._id as Types.ObjectId).toString();

  const accessToken = await generateAccessToken({ userId });
  const refreshToken = await generateRefreshToken({ userId });

  // TODO: Store refresh token in database
  // await new RefreshToken({ userId, token: refreshToken, expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) }).save();

  const { password: _, ...userWithoutPassword } = user;
  return { accessToken, refreshToken, user: userWithoutPassword };
};

export const signup = async (userData: IUser & { password: string }) => {
  try {
    const existingUser = await User.findOne({ email: userData.email }).lean();
    if (existingUser) {
      return { message: 'User already exists with this email' };
    }

    const hashedPassword = await bcrypt.hash(userData.password, 12);
    const newUser = new User({ ...userData, password: hashedPassword });

    await newUser.save();
    const { password: _, ...userWithoutPassword } = newUser.toObject();
    return { user: userWithoutPassword };
  } catch (error: any) {
    throw new AppError('Signup failed: ' + error.message, 400);
  }
};

export const forgotPassword = async (email: string): Promise<string> => {
  const user = await User.findOne({ email });
  if (!user) {
    throw new AppError('No user found with that email address', 404);
  }

  // Generate reset token
  const resetToken = crypto.randomBytes(32).toString('hex');
  const hashedToken = crypto.createHash('sha256').update(resetToken).digest('hex');

  // TODO: Store reset token in database with expiration
  // await new PasswordReset({ userId: user._id, token: hashedToken, expiresAt: Date.now() + 10 * 60 * 1000 }).save();

  return resetToken;
};

export const resetPassword = async (token: string, newPassword: string) => {
  // Validate password strength
  if (!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[\\W_]).{8,}$/.test(newPassword)) {
    throw new AppError('Password must be at least 8 characters long and contain lowercase, uppercase, number, and special character', 400);
  }

  const hashedToken = crypto.createHash('sha256').update(token).digest('hex');

  // TODO: Find and validate reset token
  // const resetRecord = await PasswordReset.findOne({ token: hashedToken, expiresAt: { $gt: Date.now() } });
  // if (!resetRecord) throw new AppError('Invalid or expired reset token', 400);

  // TODO: Update user password
  // const user = await User.findById(resetRecord.userId);
  // if (!user) throw new AppError('User not found', 404);
  // user.password = await bcrypt.hash(newPassword, 12);
  // await user.save();
  // await PasswordReset.deleteOne({ _id: resetRecord._id });

  return 'Password has been reset successfully';
};

export const refreshAccessToken = async (refreshToken: string) => {
  try {
    const decoded = await verifyRefreshToken(refreshToken);
    if (!decoded) {
      throw new AppError('Invalid refresh token', 401);
    }

    // TODO: Validate stored refresh token
    // const storedToken = await RefreshToken.findOne({ token: refreshToken });
    // if (!storedToken) throw new AppError('Invalid refresh token', 401);

    return await generateAccessToken({ userId: decoded.userId });
  } catch (error) {
    throw new AppError('Invalid or expired refresh token', 401);
  }
};

export const logout = async (refreshToken: string) => {
  // TODO: Remove refresh token from database
  // await RefreshToken.deleteOne({ token: refreshToken });
  return true;
};`;

  // Generate token utilities
  const tokenUtilsContent = `import jwt from 'jsonwebtoken';

const JWT_SECRET = process.env.JWT_SECRET!;
const JWT_REFRESH_SECRET = process.env.JWT_REFRESH_SECRET || process.env.JWT_SECRET!;

export interface TokenPayload {
  userId: string;
  exp?: number;
}

export const generateAccessToken = async (payload: TokenPayload): Promise<string> => {
  const accessTokenExpiry = process.env.JWT_EXPIRES_IN || '15m';
  return jwt.sign(payload, JWT_SECRET, { expiresIn: accessTokenExpiry });
};

export const generateRefreshToken = async (payload: TokenPayload): Promise<string> => {
  const refreshTokenExpiry = process.env.JWT_REFRESH_EXPIRES_IN || '7d';
  return jwt.sign(payload, JWT_REFRESH_SECRET, { expiresIn: refreshTokenExpiry });
};

export const verifyAccessToken = async (token: string): Promise<TokenPayload | null> => {
  try {
    const decoded = jwt.verify(token, JWT_SECRET) as TokenPayload;
    return decoded;
  } catch (error) {
    return null;
  }
};

export const verifyRefreshToken = async (token: string): Promise<TokenPayload | null> => {
  try {
    const decoded = jwt.verify(token, JWT_REFRESH_SECRET) as TokenPayload;
    return decoded;
  } catch (error) {
    return null;
  }
};`;

  await fs.writeFile(path.join(srcPath, 'controllers', 'authController.ts'), authControllerContent);
  await fs.writeFile(path.join(srcPath, 'middleware', 'auth.ts'), authMiddlewareContent);
  await fs.writeFile(path.join(srcPath, 'middleware', 'errorHandler.ts'), errorHandlerContent);
  await fs.writeFile(path.join(srcPath, 'services', 'authService.ts'), authServiceContent);
  await fs.writeFile(path.join(srcPath, 'utils', 'tokenUtils.ts'), tokenUtilsContent);
  await fs.writeFile(path.join(projectPath, '.env'), envContent);
  
  console.log(colors.green('✅ Created file: src/controllers/authController.ts'));
  console.log(colors.green('✅ Created file: src/middleware/auth.ts'));
  console.log(colors.green('✅ Created file: src/middleware/errorHandler.ts'));
  console.log(colors.green('✅ Created file: src/services/authService.ts'));
  console.log(colors.green('✅ Created file: src/utils/tokenUtils.ts'));
  console.log(colors.green('✅ Created file: .env'));
};

// Generate TypeScript server template
const generateServerTemplate = (projectName: string): string => {
  return `import express, { Application, Request, Response, NextFunction } from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import dotenv from 'dotenv';

import { connectDB } from './config/database';
import { errorHandler } from './middleware/errorHandler';
import { setupSwagger } from './config/swagger';

// Import routes
import indexRoutes from './routes/index';
import authRoutes from './routes/auth';

dotenv.config();

const app: Application = express();
const PORT: number = parseInt(process.env.PORT || '8000');

// Connect to MongoDB
connectDB();

// Security middleware
app.use(helmet());
app.use(cors({
  origin: process.env.FRONTEND_URL || 'http://localhost:5000',
  credentials: true
}));

// Rate limiting
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100, // limit each IP to 100 requests per windowMs
  message: 'Too many requests from this IP, please try again later.'
});
app.use('/api/', limiter);

// Body parsing middleware
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));

// Setup Swagger documentation
setupSwagger(app);

// Routes
app.use('/api', indexRoutes);
app.use('/api/auth', authRoutes);

// Health check endpoint
app.get('/health', (req: Request, res: Response) => {
  res.status(200).json({ 
    status: 'OK', 
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
    environment: process.env.NODE_ENV || 'development',
    version: getVersion()
  });
});

// Error handling middleware (should be last)
app.use(errorHandler);

// 404 handler
app.use('*', (req: Request, res: Response) => {
  res.status(404).json({ 
    success: false, 
    message: 'Route not found',
    path: req.originalUrl
  });
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(\`🚀 Server running on port \${PORT}\`);
  console.log(\`📱 Environment: \${process.env.NODE_ENV || 'development'}\`);
  console.log(\`📚 API Documentation: http://localhost:\${PORT}/api-docs\`);
});

export default app;
`;
};

program
  .name('koti')
  .description('⚠️  DEVELOPMENT VERSION: CLI tool to generate TypeScript Bun API projects with Express and MongoDB\n    This is an initial development release and may contain errors or bugs.\n    Use at your own discretion and always review generated code before production use.')
  .version(getVersion());

// TypeScript Model Generation Command
program
  .command('create:model')
  .argument('<model-name>', 'Name of the model to create')
  .description('Create a new TypeScript model with schema registry')
  .action(async (modelName: string) => {
    try {
      console.log(colors.blue(`🏗️ Creating TypeScript model: ${capitalize(modelName)}`));
      
      const rl = createReadlineInterface();
      const fields: { name: string; type: string; required: boolean; unique?: boolean; indexed?: boolean; default?: string }[] = [];
      
      console.log(colors.cyan('\n📝 Define your model fields:'));
      console.log(colors.dim('Available data types:'));
      console.log(colors.dim('1. String    2. Number    3. Date      4. Boolean'));
      console.log(colors.dim('5. ObjectId  6. Array     7. Mixed     8. JSON'));
      console.log(colors.dim('Type "done" when finished\n'));

      const dataTypes = ['String', 'Number', 'Date', 'Boolean', 'ObjectId', 'Array', 'Mixed', 'JSON'];

      let fieldName = '';
      while (fieldName !== 'done') {
        fieldName = await askQuestion(rl, colors.yellow('Field name (or "done" to finish): '));
        
        if (fieldName === 'done') break;
        if (!fieldName.trim()) continue;

        // Show data type options
        console.log(colors.cyan('\nSelect data type:'));
        dataTypes.forEach((type, index) => {
          console.log(colors.dim(`${index + 1}. ${type}`));
        });
        
        const typeChoice = await askQuestion(rl, colors.yellow('Enter type number (1-8): '));
        const typeIndex = parseInt(typeChoice) - 1;
        
        if (typeIndex < 0 || typeIndex >= dataTypes.length) {
          console.log(colors.red('❌ Invalid choice. Please select 1-8.'));
          continue;
        }
        
        const fieldType = dataTypes[typeIndex];
        const isRequired = (await askQuestion(rl, colors.yellow('Required? (y/n): '))).toLowerCase() === 'y';
        const isUnique = (await askQuestion(rl, colors.yellow('Unique? (y/n): '))).toLowerCase() === 'y';
        const isIndexed = (await askQuestion(rl, colors.yellow('Add index? (y/n): '))).toLowerCase() === 'y';
        const defaultValue = await askQuestion(rl, colors.yellow('Default value (press enter to skip): '));

        fields.push({
          name: fieldName,
          type: fieldType,
          required: isRequired,
          unique: isUnique || undefined,
          indexed: isIndexed || undefined,
          default: defaultValue || undefined
        });

        console.log(colors.green(`✅ Added field: ${fieldName} (${fieldType})`));
      }

      // Ask if user wants to generate CRUD operations
      const generateCRUD = (await askQuestion(rl, colors.cyan('\n🔧 Generate CRUD operations (controller, service, routes)? (y/n): '))).toLowerCase() === 'y';
      
      rl.close();

      // Generate TypeScript model file
      const modelContent = generateTypeScriptModel(modelName, fields);
      const modelPath = path.join(process.cwd(), 'src', 'models', `${capitalize(modelName)}.ts`);
      
      await fs.ensureDir(path.dirname(modelPath));
      await fs.writeFile(modelPath, modelContent);
      
      console.log(colors.green(`✅ Created TypeScript model: src/models/${capitalize(modelName)}.ts`));

      if (generateCRUD) {

      // Generate CRUD Controller
      const controllerContent = generateCRUDController(modelName, fields);
      const controllerPath = path.join(process.cwd(), 'src', 'controllers', `${modelName}Controller.ts`);
      
      await fs.ensureDir(path.dirname(controllerPath));
      await fs.writeFile(controllerPath, controllerContent);
      
      console.log(colors.green(`✅ Created TypeScript controller: src/controllers/${modelName}Controller.ts`));

      // Generate CRUD Service
      const serviceContent = generateCRUDService(modelName, fields);
      const servicePath = path.join(process.cwd(), 'src', 'services', `${modelName}Service.ts`);
      
      await fs.ensureDir(path.dirname(servicePath));
      await fs.writeFile(servicePath, serviceContent);
      
      console.log(colors.green(`✅ Created TypeScript service: src/services/${modelName}Service.ts`));

      // Generate CRUD Routes
      const routeContent = generateCRUDRoutes(modelName);
      const routePath = path.join(process.cwd(), 'src', 'routes', `${modelName}.ts`);
      
      await fs.ensureDir(path.dirname(routePath));
      await fs.writeFile(routePath, routeContent);
      
      console.log(colors.green(`✅ Created TypeScript routes: src/routes/${modelName}.ts`));

      // Update main routes/index.ts to register the new route
      await updateMainRoutes(modelName);
      
      console.log(colors.green(`✅ Registered route in src/routes/index.ts`));
      
      console.log(colors.cyan('\n📚 Generated CRUD system includes:'));
      console.log('   • Model with Mongoose schema and TypeScript types');
      console.log('   • Controller with full CRUD operations (GET, POST, PUT, DELETE)');
      console.log('   • Service layer with business logic and pagination');
      console.log('   • Routes with Swagger documentation');
      console.log('   • Pagination support (configurable in .env - DEFAULT_PAGE_LIMIT)');
      console.log('   • Automatic route registration');
      
        console.log(colors.yellow('\n🔧 Next steps:'));
        console.log('   • Update .env file with DEFAULT_PAGE_LIMIT (default: 10)');
        console.log('   • Run TypeScript compilation: npm run build');
        console.log('   • Test the CRUD endpoints in your API');
      } else {
        console.log(colors.cyan('\n📚 Model created successfully!'));
        console.log(colors.yellow('🔧 Next steps:'));
        console.log('   • Import the model in your controllers');
        console.log('   • Use "koti create:controller", "koti create:service" for CRUD operations');
        console.log('   • Run TypeScript compilation: npm run build');
      }

    } catch (error) {
      console.error(colors.red('❌ Error creating model:'), (error as Error).message);
      process.exit(1);
    }
  });

// TypeScript Enum Generation Command
program
  .command('create:enum')
  .argument('<enum-name>', 'Name of the enum to create')
  .description('Create a new TypeScript enum')
  .action(async (enumName: string) => {
    try {
      console.log(colors.blue(`📋 Creating TypeScript enum: ${capitalize(enumName)}`));
      
      const rl = createReadlineInterface();
      const enumType = await askQuestion(rl, colors.yellow('Enum type (string/number): '));
      
      if (!enumTypes.includes(enumType)) {
        console.log(colors.red('❌ Invalid enum type. Use "string" or "number"'));
        rl.close();
        return;
      }

      const values: { key: string; value: string | number }[] = [];
      
      console.log(colors.cyan('\n📝 Define your enum values:'));
      console.log(colors.dim('Type "done" when finished\n'));

      let key = '';
      while (key !== 'done') {
        key = await askQuestion(rl, colors.yellow('Enum key (or "done" to finish): '));
        
        if (key === 'done') break;
        if (!key.trim()) continue;

        let value: string | number;
        if (enumType === 'string') {
          value = await askQuestion(rl, colors.yellow(`String value for ${key}: `));
        } else {
          const numValue = await askQuestion(rl, colors.yellow(`Number value for ${key}: `));
          value = parseInt(numValue);
        }

        values.push({ key: key.toUpperCase(), value });
        console.log(colors.green(`✅ Added: ${key.toUpperCase()} = ${value}`));
      }

      rl.close();

      // Generate TypeScript enum file
      const enumContent = generateTypeScriptEnum(enumName, enumType as 'string' | 'number', values);
      const enumPath = path.join(process.cwd(), 'src', 'enums', `${capitalize(enumName)}.ts`);
      
      await fs.ensureDir(path.dirname(enumPath));
      await fs.writeFile(enumPath, enumContent);
      
      console.log(colors.green(`✅ Created TypeScript enum: src/enums/${capitalize(enumName)}.ts`));

    } catch (error) {
      console.error(colors.red('❌ Error creating enum:'), (error as Error).message);
      process.exit(1);
    }
  });

// TypeScript Controller Generation Command
program
  .command('create:controller')
  .argument('<controller-name>', 'Name of the controller to create')
  .description('Create a new TypeScript controller')
  .action(async (controllerName: string) => {
    try {
      console.log(colors.blue(`🎮 Creating TypeScript controller: ${capitalize(controllerName)}`));
      
      const controllerContent = generateTypeScriptController(controllerName);
      const controllerPath = path.join(process.cwd(), 'src', 'controllers', `${toCamelCase(controllerName)}Controller.ts`);
      
      await fs.ensureDir(path.dirname(controllerPath));
      await fs.writeFile(controllerPath, controllerContent);
      
      console.log(colors.green(`✅ Created TypeScript controller: src/controllers/${toCamelCase(controllerName)}Controller.ts`));
      
    } catch (error) {
      console.error(colors.red('❌ Error creating controller:'), (error as Error).message);
      process.exit(1);
    }
  });

// TypeScript Service Generation Command
program
  .command('create:service')
  .argument('<service-name>', 'Name of the service to create')
  .description('Create a new TypeScript service')
  .action(async (serviceName: string) => {
    try {
      console.log(colors.blue(`⚙️ Creating TypeScript service: ${capitalize(serviceName)}`));
      
      const serviceContent = generateTypeScriptService(serviceName);
      const servicePath = path.join(process.cwd(), 'src', 'services', `${toCamelCase(serviceName)}Service.ts`);
      
      await fs.ensureDir(path.dirname(servicePath));
      await fs.writeFile(servicePath, serviceContent);
      
      console.log(colors.green(`✅ Created TypeScript service: src/services/${toCamelCase(serviceName)}Service.ts`));
      
    } catch (error) {
      console.error(colors.red('❌ Error creating service:'), (error as Error).message);
      process.exit(1);
    }
  });

// TypeScript Middleware Generation Command
program
  .command('create:middleware')
  .argument('<middleware-name>', 'Name of the middleware to create')
  .description('Create a new TypeScript middleware')
  .action(async (middlewareName: string) => {
    try {
      console.log(colors.blue(`🛡️ Creating TypeScript middleware: ${toCamelCase(middlewareName)}`));
      
      const middlewareContent = generateTypeScriptMiddleware(middlewareName);
      const middlewarePath = path.join(process.cwd(), 'src', 'middleware', `${toCamelCase(middlewareName)}.ts`);
      
      await fs.ensureDir(path.dirname(middlewarePath));
      await fs.writeFile(middlewarePath, middlewareContent);
      
      console.log(colors.green(`✅ Created TypeScript middleware: src/middleware/${toCamelCase(middlewareName)}.ts`));
      
    } catch (error) {
      console.error(colors.red('❌ Error creating middleware:'), (error as Error).message);
      process.exit(1);
    }
  });

// Legacy JavaScript Model Command (for backward compatibility)
program
  .command('model')
  .argument('<model-name>', 'Name of the model to create')
  .description('Create a new model with interactive setup (legacy)')
  .action(async (modelName: string) => {
    try {
      console.log(colors.yellow('⚠️ Using legacy JavaScript model generation'));
      console.log(colors.blue(`🏗️ Creating model: ${capitalize(modelName)}`));
      
      // Legacy implementation would go here - simplified for TypeScript conversion
      console.log(colors.dim('Use "koti create:model" for TypeScript models'));
      
    } catch (error) {
      console.error(colors.red('❌ Error creating model:'), (error as Error).message);
      process.exit(1);
    }
  });

program
  .command('new')
  .alias('create')
  .argument('<project-name>', 'Name of the project to create')
  .description('Create a new TypeScript Bun API project')
  .action(async (projectName: string) => {
    try {
      console.log(colors.blue(`🚀 Creating TypeScript Bun API project: ${projectName}`));
      
      const projectPath = path.join(process.cwd(), projectName);
      console.log(colors.dim(`📁 Project directory: ${projectPath}`));
      
      // Create project directory
      await fs.ensureDir(projectPath);
      
      // Create src directory structure
      const srcPath = path.join(projectPath, 'src');
      const directories = [
        'config', 'controllers', 'middleware', 'models', 
        'routes', 'types', 'utils', 'services', 'schemas', 'enums'
      ];
      
      for (const dir of directories) {
        await fs.ensureDir(path.join(srcPath, dir));
        console.log(colors.green(`✅ Created directory: src/${dir}/`));
      }

      // Generate files from templates
      for (const [fileName, content] of Object.entries(projectTemplates)) {
        const filePath = path.join(projectPath, fileName);
        const processedContent = content.replace(/{{PROJECT_NAME}}/g, projectName);
        await fs.writeFile(filePath, processedContent);
        console.log(colors.green(`✅ Created file: ${fileName}`));
      }

      // Generate TypeScript server file
      const serverContent = generateServerTemplate(projectName);
      await fs.writeFile(path.join(srcPath, 'server.ts'), serverContent);
      console.log(colors.green('✅ Created file: src/server.ts'));

      // Copy all TypeScript template files
      const templatePath = path.join(__dirname, '..', 'templates');
      const templateSrcPath = path.join(templatePath, 'src');
      const projectSrcPath = path.join(projectPath, 'src');
      
      // Copy the entire src directory structure
      if (await fs.pathExists(templateSrcPath)) {
        await fs.copy(templateSrcPath, projectSrcPath);
        console.log(colors.green('✅ Copied TypeScript source files'));
      }
      
      // Copy additional template files
      const additionalFiles = [
        'tsconfig.json',
        '.env',
        '.gitignore'
      ];
      
      for (const fileName of additionalFiles) {
        const templateFilePath = path.join(templatePath, fileName);
        const projectFilePath = path.join(projectPath, fileName);
        
        if (await fs.pathExists(templateFilePath)) {
          let content = await fs.readFile(templateFilePath, 'utf-8');
          content = content.replace(/{{PROJECT_NAME}}/g, projectName);
          await fs.writeFile(projectFilePath, content);
          console.log(colors.green(`✅ Created file: ${fileName}`));
        }
      }

      // Generate additional necessary files
      await generateEssentialFiles(projectPath, projectName);
      
      console.log(colors.green('\n🎉 TypeScript project created successfully!'));
      
      // Automatically install dependencies
      console.log(colors.blue('\n📦 Installing dependencies...'));
      let installSuccess = false;
      
      // Simple approach to run bun install
      try {
        const { execSync } = require('child_process');
        console.log(colors.dim('Running: bun install'));
        
        const result = execSync('bun install', { 
          cwd: projectPath,
          stdio: 'inherit',
          timeout: 45000 // 45 second timeout
        });
        
        console.log(colors.green('✅ Dependencies installed successfully with bun!'));
        installSuccess = true;
        
      } catch (error) {
        console.log(colors.yellow('⚠️  Bun install failed, trying npm install...'));
        
        // Fallback to npm install
        try {
          const { execSync } = require('child_process');
          console.log(colors.dim('Running: npm install'));
          
          const result = execSync('npm install', { 
            cwd: projectPath,
            stdio: 'inherit',
            timeout: 60000 // 60 second timeout
          });
          
          console.log(colors.green('✅ Dependencies installed successfully with npm!'));
          installSuccess = true;
          
        } catch (npmError) {
          console.log(colors.red('❌ Failed to install dependencies automatically'));
          console.log(colors.yellow('   Please run "bun install" or "npm install" manually in the project directory'));
        }
      }
      
      if (installSuccess) {
        console.log(colors.green('✅ Project is ready to use!'));
      }
      
      console.log(colors.cyan('\n📋 Next steps:'));
      console.log(`   1. cd ${projectName}`);
      console.log('   2. Update .env file with your MongoDB URI and JWT secret');
      console.log('   3. Start MongoDB server');
      console.log('   4. bun run dev');
      
      console.log(colors.blue('\n📚 Useful commands:'));
      console.log('   • npm run build   - Build TypeScript to JavaScript');
      console.log('   • npm start       - Start production server');
      console.log('   • bun run dev     - Start development server with Bun');
      console.log('   • npm run dev:ts  - Start development server with ts-node');

      console.log(colors.cyan('\n🌐 Default endpoints:'));
      console.log('   • http://localhost:8000/health     - Health check');
      console.log('   • http://localhost:8000/api/       - API welcome');
      console.log('   • http://localhost:8000/api-docs   - Swagger documentation');

      console.log(colors.cyan('\n🔐 Authentication endpoints:'));
      console.log('   • POST /api/auth/register - Register user');
      console.log('   • POST /api/auth/login    - Login user');
      console.log('   • GET  /api/auth/me       - Get current user');
      
      console.log(colors.yellow('\n💡 Don\'t forget to:'));
      console.log('   • Set up your MongoDB database');
      console.log('   • Generate a secure JWT secret');
      console.log('   • Configure your environment variables');
      console.log('   • Review the generated TypeScript code');
      
      console.log(colors.red('\n⚠️  IMPORTANT DISCLAIMER:'));
      console.log(`   • This is a development version (v${getVersion()}) and may contain errors`);
      console.log('   • Review all generated code before production use');
      console.log('   • Test thoroughly in development environments');
      console.log('   • Update dependencies to latest secure versions');
      
      console.log(colors.green('\nHappy coding! 🚀'));

    } catch (error) {
      console.error(colors.red('❌ Error creating project:'), (error as Error).message);
      process.exit(1);
    }
  });

program.parse();