#!/usr/bin/env node

import { Command } from 'commander';
import * as fs from 'fs-extra';
import * as path from 'path';
import * as readline from 'readline';

interface DataType {
  mongoose: string;
  typescript: string;
}

interface ProjectTemplates {
  [key: string]: string;
}

interface Colors {
  green: (text: string) => string;
  blue: (text: string) => string;
  yellow: (text: string) => string;
  red: (text: string) => string;
  cyan: (text: string) => string;
  bold: (text: string) => string;
  dim: (text: string) => string;
}

const program = new Command();

// Console colors without chalk
const colors: Colors = {
  green: (text: string) => `\x1b[32m${text}\x1b[0m`,
  blue: (text: string) => `\x1b[34m${text}\x1b[0m`,
  yellow: (text: string) => `\x1b[33m${text}\x1b[0m`,
  red: (text: string) => `\x1b[31m${text}\x1b[0m`,
  cyan: (text: string) => `\x1b[36m${text}\x1b[0m`,
  bold: (text: string) => `\x1b[1m${text}\x1b[0m`,
  dim: (text: string) => `\x1b[2m${text}\x1b[0m`
};

// Available Mongoose data types with TypeScript equivalents
const availableDataTypes: DataType[] = [
  { mongoose: 'String', typescript: 'string' },
  { mongoose: 'Number', typescript: 'number' },
  { mongoose: 'Date', typescript: 'Date' },
  { mongoose: 'Boolean', typescript: 'boolean' },
  { mongoose: 'ObjectId', typescript: 'Types.ObjectId' },
  { mongoose: 'Array', typescript: 'Array' },
  { mongoose: 'Mixed', typescript: 'any' },
  { mongoose: 'Decimal128', typescript: 'Types.Decimal128' },
  { mongoose: 'Map', typescript: 'Map<string, any>' },
  { mongoose: 'Schema', typescript: 'Schema' }
];

// Available enum types for generation
const enumTypes: string[] = ['string', 'number'];

// Helper function to create readline interface
const createReadlineInterface = (): readline.Interface => {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
};

// Helper function to ask question
const askQuestion = (rl: readline.Interface, question: string): Promise<string> => {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
};

// Helper function to capitalize first letter
const capitalize = (str: string): string => {
  return str.charAt(0).toUpperCase() + str.slice(1);
};

// Helper function to convert to camelCase
const toCamelCase = (str: string): string => {
  return str.charAt(0).toLowerCase() + str.slice(1);
};

// Helper function to convert to kebab-case
const toKebabCase = (str: string): string => {
  return str.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
};

// Helper function to read existing schemas
const readExistingSchemas = async (projectPath: string): Promise<string[]> => {
  const schemasPath = path.join(projectPath, 'src', 'schemas');
  if (!await fs.pathExists(schemasPath)) {
    return [];
  }
  
  const files = await fs.readdir(schemasPath);
  return files
    .filter(file => file.endsWith('.ts'))
    .map(file => file.replace('.ts', ''));
};

// Project templates as a constant object
const projectTemplates: ProjectTemplates = {
  'package.json': JSON.stringify({
    name: "{{PROJECT_NAME}}",
    version: "1.0.0",
    description: "Bun API project with Express and MongoDB",
    main: "dist/server.js",
    scripts: {
      build: "tsc",
      start: "node dist/server.js",
      dev: "bun --watch src/server.ts",
      "dev:ts": "ts-node src/server.ts",
      test: "echo \"Error: no test specified\" && exit 1"
    },
    dependencies: {
      "express": "^4.18.2",
      "mongoose": "^8.0.0",
      "dotenv": "^16.3.1",
      "cors": "^2.8.5",
      "helmet": "^7.1.0",
      "bcryptjs": "^2.4.3",
      "jsonwebtoken": "^9.0.2",
      "express-rate-limit": "^7.1.5",
      "joi": "^17.11.0",
      "swagger-jsdoc": "^6.2.8",
      "swagger-ui-express": "^5.0.0"
    },
    devDependencies: {
      "typescript": "^5.3.2",
      "@types/express": "^4.17.21",
      "@types/node": "^20.10.0",
      "@types/cors": "^2.8.17",
      "@types/bcryptjs": "^2.4.6",
      "@types/jsonwebtoken": "^9.0.5",
      "@types/swagger-jsdoc": "^6.0.4",
      "@types/swagger-ui-express": "^4.1.6",
      "ts-node": "^10.9.1",
      "nodemon": "^3.0.2"
    },
    keywords: ["bun", "express", "mongodb", "api", "typescript"],
    author: "mynenikoteshwarrao",
    license: "MIT",
    disclaimer: "Generated by Koti CLI v1.0.3 - Development version. Code provided as-is without warranty. Review before production use."
  }, null, 2),

  'tsconfig.json': JSON.stringify({
    compilerOptions: {
      target: "ES2020",
      module: "CommonJS",
      lib: ["ES2020"],
      outDir: "./dist",
      rootDir: "./src",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      declaration: true,
      sourceMap: true,
      removeComments: false,
      noImplicitAny: true,
      strictNullChecks: true,
      moduleResolution: "node",
      allowSyntheticDefaultImports: true,
      experimentalDecorators: true,
      emitDecoratorMetadata: true
    },
    include: [
      "src/**/*"
    ],
    exclude: [
      "node_modules",
      "dist"
    ]
  }, null, 2),

  'README.md': `# {{PROJECT_NAME}}

A modern TypeScript API built with Bun, Express.js, and MongoDB.

## ⚠️ Development Disclaimer

**This project was generated using Koti CLI (Development Version 1.0.3)**

This is an initial development release and may contain errors, bugs, or security vulnerabilities. Please:
- Review all generated code before using in production
- Test thoroughly in development environments
- Update dependencies to latest versions
- Implement proper security measures for production use
- Use at your own discretion and risk

Generated code is provided "as-is" without warranty of any kind.

## 🚀 Features

- **TypeScript**: Full type safety and modern JavaScript features
- **Bun Runtime**: Lightning-fast JavaScript runtime
- **Express.js**: Minimal and flexible web framework
- **MongoDB**: NoSQL database with Mongoose ODM
- **Authentication**: JWT-based authentication system
- **Security**: Helmet, CORS, rate limiting
- **Error Handling**: Centralized error handling
- **Validation**: Joi request validation and sanitization
- **API Documentation**: Swagger/OpenAPI 3.0 documentation
- **Environment Config**: Environment-based configuration

## 📋 Prerequisites

- [Bun](https://bun.sh/) installed
- [MongoDB](https://www.mongodb.com/) installed and running
- Node.js 16+ (for development tools)
- TypeScript knowledge recommended

## 🛠️ Installation

1. **Clone the repository**
   \`\`\`bash
   git clone <repository-url>
   cd {{PROJECT_NAME}}
   \`\`\`

2. **Install dependencies**
   \`\`\`bash
   bun install
   \`\`\`

3. **Set up environment variables**
   \`\`\`bash
   cp .env.example .env
   \`\`\`
   
   Edit \`.env\` file with your configuration:
   \`\`\`env
   NODE_ENV=development
   PORT=8000
   MONGODB_URI=mongodb://localhost:27017/{{PROJECT_NAME}}
   JWT_SECRET=your-super-secret-jwt-key
   \`\`\`

4. **Start MongoDB**
   \`\`\`bash
   # On macOS with Homebrew
   brew services start mongodb-community
   
   # On Linux
   sudo systemctl start mongod
   \`\`\`

## 🚀 Usage

### Development

\`\`\`bash
# Development with Bun (recommended)
bun run dev

# Development with TypeScript compilation
npm run dev:ts

# Build TypeScript
npm run build

# Production
npm start
\`\`\`

### API Documentation

- **Swagger UI**: http://localhost:8000/api-docs
- **Health Check**: http://localhost:8000/health
- **API Status**: http://localhost:8000/api/status

### Default Endpoints

- \`GET /health\` - Health check
- \`GET /api/\` - API welcome message
- \`GET /api/status\` - API status information
- \`GET /api-docs\` - Interactive API documentation

### Authentication Endpoints

- \`POST /api/auth/register\` - Register new user
- \`POST /api/auth/login\` - User login
- \`GET /api/auth/me\` - Get current user profile

## 📁 Project Structure

\`\`\`
{{PROJECT_NAME}}/
├── src/
│   ├── config/
│   │   ├── database.ts         # MongoDB connection
│   │   └── swagger.ts          # Swagger configuration
│   ├── controllers/
│   │   ├── authController.ts   # Authentication logic
│   │   └── index.ts           # Controller exports
│   ├── middleware/
│   │   ├── auth.ts            # JWT authentication
│   │   ├── errorHandler.ts    # Error handling
│   │   ├── rateLimit.ts       # Rate limiting
│   │   └── validation.ts      # Joi validation
│   ├── models/
│   │   ├── User.ts            # User model
│   │   └── index.ts           # Model exports
│   ├── routes/
│   │   ├── auth.ts            # Auth routes
│   │   ├── index.ts           # Main routes
│   │   └── api.ts             # API routes
│   ├── types/
│   │   └── api.ts             # TypeScript definitions
│   ├── utils/
│   │   ├── AppError.ts        # Custom error class
│   │   ├── logger.ts          # Logging utility
│   │   └── responseHelper.ts  # Response helpers
│   └── server.ts              # Main server file
├── dist/                      # Compiled JavaScript
├── .env                       # Environment variables
├── .gitignore                 # Git ignore rules
├── package.json               # Dependencies
├── tsconfig.json              # TypeScript config
└── README.md                  # This file
\`\`\`

## 🔧 Development

### Adding New Features

Use the Koti CLI to generate new components:

\`\`\`bash
# Create new model
koti create:model Product

# Create new controller
koti create:controller Product

# Create new service
koti create:service Email

# Create new middleware
koti create:middleware Logger

# Create new enum
koti create:enum Status
\`\`\`

### TypeScript Features

- **Full Type Safety**: All code is written in TypeScript
- **Interface Definitions**: Clear contracts for all data structures
- **Enum Support**: Type-safe enumerations
- **Generic Types**: Reusable type definitions
- **Decorators**: Support for experimental decorators

## 🛡️ Security Features

- **JWT Authentication**: Secure token-based authentication
- **Password Hashing**: bcrypt for secure password storage
- **Rate Limiting**: Protection against brute force attacks
- **CORS**: Cross-origin resource sharing configuration
- **Helmet**: Security headers middleware
- **Input Validation**: Joi validation for all inputs

## 📊 Monitoring & Logging

- **Health Checks**: Built-in health check endpoints
- **Request Logging**: Detailed request/response logging
- **Error Tracking**: Comprehensive error logging
- **Performance Monitoring**: Request timing and metrics

## 🧪 Testing

\`\`\`bash
# Run tests (when implemented)
npm test

# Type checking
npx tsc --noEmit

# Linting (when configured)
npm run lint
\`\`\`

## 🚀 Deployment

### Production Build

\`\`\`bash
# Build for production
npm run build

# Start production server
npm start
\`\`\`

### Environment Variables

Set the following environment variables for production:

- \`NODE_ENV=production\`
- \`PORT=8000\`
- \`MONGODB_URI=your-production-mongodb-uri\`
- \`JWT_SECRET=your-secure-jwt-secret\`

## 📄 License

MIT License - see LICENSE file for details.

## 🤝 Contributing

1. Fork the repository
2. Create a feature branch
3. Make your changes
4. Add tests if applicable
5. Submit a pull request

## 📞 Support

For support, please open an issue in the repository or contact the maintainer.

---

Generated with ❤️ by [Koti CLI](https://www.npmjs.com/package/koti)
`
};

// Generate TypeScript Model
const generateTypeScriptModel = (modelName: string, fields: any[]): string => {
  const capitalizedName = capitalize(modelName);
  const fieldsCode = fields.map(field => {
    const options = [];
    if (field.required) options.push('required: true');
    if (field.unique) options.push('unique: true');
    if (field.default) options.push(`default: ${field.type === 'String' ? `'${field.default}'` : field.default}`);
    
    const optionsString = options.length > 0 ? `, { ${options.join(', ')} }` : '';
    return `  ${field.name}: { type: ${field.type}${optionsString} }`;
  }).join(',\n');

  return `import { Schema, model, Document, Types } from 'mongoose';

export interface I${capitalizedName} extends Document {
${fields.map(field => {
  const tsType = field.type === 'ObjectId' ? 'Types.ObjectId' : 
                 field.type === 'String' ? 'string' :
                 field.type === 'Number' ? 'number' :
                 field.type === 'Boolean' ? 'boolean' :
                 field.type === 'Date' ? 'Date' :
                 field.type === 'Array' ? 'any[]' : 'any';
  return `  ${field.name}: ${tsType};`;
}).join('\n')}
}

const ${capitalizedName}Schema = new Schema<I${capitalizedName}>({
${fieldsCode}
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

export const ${capitalizedName} = model<I${capitalizedName}>('${capitalizedName}', ${capitalizedName}Schema);
export default ${capitalizedName};
`;
};

// Generate TypeScript Enum
const generateTypeScriptEnum = (enumName: string, enumType: 'string' | 'number', values: { key: string; value: string | number }[]): string => {
  const capitalizedName = capitalize(enumName);
  
  const enumValues = values.map(({ key, value }) => {
    if (enumType === 'string') {
      return `  ${key} = '${value}'`;
    }
    return `  ${key} = ${value}`;
  }).join(',\n');

  return `export enum ${capitalizedName} {
${enumValues}
}

export default ${capitalizedName};
`;
};

// Generate TypeScript Controller
const generateTypeScriptController = (controllerName: string): string => {
  const capitalizedName = capitalize(controllerName);
  const camelCaseName = toCamelCase(controllerName);
  
  return `import { Request, Response, NextFunction } from 'express';
import { ApiResponse, PaginatedResponse, AuthenticatedRequest } from '../types/api';
import { AppError } from '../utils/AppError';

export class ${capitalizedName}Controller {
  /**
   * Get all ${controllerName}s with pagination
   * @route GET /api/${toKebabCase(controllerName)}
   */
  public async getAll(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const page = parseInt(req.query.page as string) || 1;
      const limit = parseInt(req.query.limit as string) || 10;
      const skip = (page - 1) * limit;

      // TODO: Implement actual data fetching logic
      const data = []; // Replace with actual data fetching
      const total = 0; // Replace with actual count

      const response: PaginatedResponse = {
        success: true,
        message: '${capitalizedName}s retrieved successfully',
        data,
        pagination: {
          page,
          limit,
          total,
          totalPages: Math.ceil(total / limit),
          hasNext: page < Math.ceil(total / limit),
          hasPrev: page > 1
        }
      };

      res.status(200).json(response);
    } catch (error) {
      next(new AppError(\`Error fetching ${controllerName}s\`, 500));
    }
  }

  /**
   * Get single ${controllerName} by ID
   * @route GET /api/${toKebabCase(controllerName)}/:id
   */
  public async getById(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const { id } = req.params;

      // TODO: Implement actual data fetching logic
      const data = null; // Replace with actual data fetching

      if (!data) {
        return next(new AppError('${capitalizedName} not found', 404));
      }

      const response: ApiResponse = {
        success: true,
        message: '${capitalizedName} retrieved successfully',
        data
      };

      res.status(200).json(response);
    } catch (error) {
      next(new AppError(\`Error fetching ${controllerName}\`, 500));
    }
  }

  /**
   * Create new ${controllerName}
   * @route POST /api/${toKebabCase(controllerName)}
   */
  public async create(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
    try {
      const { body } = req;

      // TODO: Implement validation and creation logic
      const data = body; // Replace with actual creation logic

      const response: ApiResponse = {
        success: true,
        message: '${capitalizedName} created successfully',
        data
      };

      res.status(201).json(response);
    } catch (error) {
      next(new AppError(\`Error creating ${controllerName}\`, 400));
    }
  }

  /**
   * Update ${controllerName} by ID
   * @route PUT /api/${toKebabCase(controllerName)}/:id
   */
  public async update(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
    try {
      const { id } = req.params;
      const { body } = req;

      // TODO: Implement actual update logic
      const data = body; // Replace with actual update logic

      const response: ApiResponse = {
        success: true,
        message: '${capitalizedName} updated successfully',
        data
      };

      res.status(200).json(response);
    } catch (error) {
      next(new AppError(\`Error updating ${controllerName}\`, 400));
    }
  }

  /**
   * Delete ${controllerName} by ID
   * @route DELETE /api/${toKebabCase(controllerName)}/:id
   */
  public async delete(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
    try {
      const { id } = req.params;

      // TODO: Implement actual deletion logic

      const response: ApiResponse = {
        success: true,
        message: '${capitalizedName} deleted successfully'
      };

      res.status(200).json(response);
    } catch (error) {
      next(new AppError(\`Error deleting ${controllerName}\`, 400));
    }
  }
}

export default new ${capitalizedName}Controller();
`;
};

// Generate TypeScript Service
const generateTypeScriptService = (serviceName: string): string => {
  const capitalizedName = capitalize(serviceName);
  
  return `import { AppError } from '../utils/AppError';

export class ${capitalizedName}Service {
  /**
   * Service method example
   * @param data - Input data
   * @returns Promise<any>
   */
  public async performOperation(data: any): Promise<any> {
    try {
      // TODO: Implement service logic here
      return data;
    } catch (error) {
      throw new AppError(\`${capitalizedName} service error: \${error}\`, 500);
    }
  }

  /**
   * Validation method example
   * @param data - Data to validate
   * @returns boolean
   */
  public validateData(data: any): boolean {
    // TODO: Implement validation logic
    return data !== null && data !== undefined;
  }

  /**
   * Process data method example
   * @param rawData - Raw data to process
   * @returns Processed data
   */
  public processData(rawData: any): any {
    // TODO: Implement data processing logic
    return rawData;
  }
}

export default new ${capitalizedName}Service();
`;
};

// Generate TypeScript Middleware
const generateTypeScriptMiddleware = (middlewareName: string): string => {
  const camelCaseName = toCamelCase(middlewareName);
  
  return `import { Request, Response, NextFunction } from 'express';
import { AppError } from '../utils/AppError';

/**
 * ${capitalize(middlewareName)} middleware
 * @param req - Express request object
 * @param res - Express response object
 * @param next - Express next function
 */
export const ${camelCaseName} = (req: Request, res: Response, next: NextFunction): void => {
  try {
    // TODO: Implement middleware logic here
    console.log(\`${capitalize(middlewareName)} middleware executed for \${req.method} \${req.path}\`);
    
    // Example: Check some condition
    const isValid = true; // Replace with actual validation logic
    
    if (!isValid) {
      return next(new AppError('${capitalize(middlewareName)} validation failed', 400));
    }
    
    next();
  } catch (error) {
    next(new AppError(\`${capitalize(middlewareName)} middleware error\`, 500));
  }
};

export default ${camelCaseName};
`;
};

// Generate essential TypeScript files
const generateEssentialFiles = async (projectPath: string, projectName: string): Promise<void> => {
  const srcPath = path.join(projectPath, 'src');

  // Generate basic route files
  const indexRouteContent = `import { Router, Request, Response } from 'express';
import { ApiResponse } from '../types/api';

const router = Router();

/**
 * @swagger
 * /api/:
 *   get:
 *     summary: API welcome message
 *     tags: [Health]
 *     responses:
 *       200:
 *         description: Welcome message
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/ApiResponse'
 */
router.get('/', (req: Request, res: Response) => {
  const response: ApiResponse = {
    success: true,
    message: 'Welcome to ${projectName} API',
    data: {
      version: '1.0.0',
      description: 'TypeScript API built with Bun, Express, and MongoDB',
      documentation: '/api-docs'
    }
  };
  res.json(response);
});

/**
 * @swagger
 * /api/status:
 *   get:
 *     summary: API status information
 *     tags: [Health]
 *     responses:
 *       200:
 *         description: API status
 */
router.get('/status', (req: Request, res: Response) => {
  const response: ApiResponse = {
    success: true,
    message: 'API is running',
    data: {
      status: 'healthy',
      timestamp: new Date().toISOString(),
      uptime: process.uptime(),
      environment: process.env.NODE_ENV || 'development'
    }
  };
  res.json(response);
});

export default router;`;

  const authRouteContent = `import { Router } from 'express';
import authController from '../controllers/authController';
import { auth } from '../middleware/auth';

const router = Router();

/**
 * @swagger
 * /api/auth/register:
 *   post:
 *     summary: Register a new user
 *     tags: [Authentication]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - username
 *               - email
 *               - password
 *             properties:
 *               username:
 *                 type: string
 *               email:
 *                 type: string
 *               password:
 *                 type: string
 *     responses:
 *       201:
 *         description: User registered successfully
 *       400:
 *         description: Validation error
 */
router.post('/register', authController.register);

/**
 * @swagger
 * /api/auth/login:
 *   post:
 *     summary: Login user
 *     tags: [Authentication]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - email
 *               - password
 *             properties:
 *               email:
 *                 type: string
 *               password:
 *                 type: string
 *     responses:
 *       200:
 *         description: Login successful
 *       401:
 *         description: Invalid credentials
 */
router.post('/login', authController.login);

/**
 * @swagger
 * /api/auth/me:
 *   get:
 *     summary: Get current user profile
 *     tags: [Authentication]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: User profile
 *       401:
 *         description: Unauthorized
 */
router.get('/me', auth, authController.getProfile);

export default router;`;

  await fs.writeFile(path.join(srcPath, 'routes', 'index.ts'), indexRouteContent);
  await fs.writeFile(path.join(srcPath, 'routes', 'auth.ts'), authRouteContent);
  
  console.log(colors.green('✅ Created file: src/routes/index.ts'));
  console.log(colors.green('✅ Created file: src/routes/auth.ts'));

  // Generate basic auth controller
  const authControllerContent = `import { Request, Response, NextFunction } from 'express';
import { ApiResponse, AuthenticatedRequest, LoginRequest, RegisterRequest } from '../types/api';
import { AppError } from '../utils/AppError';

class AuthController {
  /**
   * Register new user
   */
  public async register(req: Request<{}, any, RegisterRequest>, res: Response, next: NextFunction): Promise<void> {
    try {
      const { username, email, password } = req.body;

      // TODO: Implement user registration logic
      const response: ApiResponse = {
        success: true,
        message: 'User registered successfully',
        data: { username, email }
      };

      res.status(201).json(response);
    } catch (error) {
      next(new AppError('Registration failed', 400));
    }
  }

  /**
   * Login user
   */
  public async login(req: Request<{}, any, LoginRequest>, res: Response, next: NextFunction): Promise<void> {
    try {
      const { email, password } = req.body;

      // TODO: Implement login logic
      const response: ApiResponse = {
        success: true,
        message: 'Login successful',
        data: { token: 'jwt-token-here' }
      };

      res.status(200).json(response);
    } catch (error) {
      next(new AppError('Login failed', 401));
    }
  }

  /**
   * Get user profile
   */
  public async getProfile(req: AuthenticatedRequest, res: Response, next: NextFunction): Promise<void> {
    try {
      const user = req.user;

      const response: ApiResponse = {
        success: true,
        message: 'Profile retrieved successfully',
        data: user
      };

      res.status(200).json(response);
    } catch (error) {
      next(new AppError('Failed to get profile', 500));
    }
  }
}

export default new AuthController();`;

  const authMiddlewareContent = `import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';
import { AuthenticatedRequest } from '../types/api';
import { AppError } from '../utils/AppError';

export const auth = (req: AuthenticatedRequest, res: Response, next: NextFunction): void => {
  try {
    const token = req.header('Authorization')?.replace('Bearer ', '');

    if (!token) {
      return next(new AppError('Access denied. No token provided.', 401));
    }

    const jwtSecret = process.env.JWT_SECRET;
    if (!jwtSecret) {
      return next(new AppError('JWT secret not configured', 500));
    }

    const decoded = jwt.verify(token, jwtSecret) as any;
    req.user = decoded;
    next();
  } catch (error) {
    next(new AppError('Invalid token', 401));
  }
};

export default auth;`;

  const errorHandlerContent = `import { Request, Response, NextFunction } from 'express';
import { AppError } from '../utils/AppError';
import { ErrorResponse } from '../types/api';

export const errorHandler = (
  error: Error | AppError,
  req: Request,
  res: Response,
  next: NextFunction
): void => {
  let statusCode = 500;
  let message = 'Internal server error';

  if (error instanceof AppError) {
    statusCode = error.statusCode;
    message = error.message;
  }

  const response: ErrorResponse = {
    success: false,
    message,
    error: error.name,
    statusCode
  };

  // Log error in development
  if (process.env.NODE_ENV === 'development') {
    console.error('Error:', error);
  }

  res.status(statusCode).json(response);
};

export default errorHandler;`;

  const envContent = `# Environment Configuration
NODE_ENV=development
PORT=8000

# Database
MONGODB_URI=mongodb://localhost:27017/${projectName}

# JWT Configuration
JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
JWT_EXPIRES_IN=7d

# Frontend URL (for CORS)
FRONTEND_URL=http://localhost:5000

# API Configuration
API_URL=http://localhost:8000`;

  await fs.writeFile(path.join(srcPath, 'controllers', 'authController.ts'), authControllerContent);
  await fs.writeFile(path.join(srcPath, 'middleware', 'auth.ts'), authMiddlewareContent);
  await fs.writeFile(path.join(srcPath, 'middleware', 'errorHandler.ts'), errorHandlerContent);
  await fs.writeFile(path.join(projectPath, '.env'), envContent);
  
  console.log(colors.green('✅ Created file: src/controllers/authController.ts'));
  console.log(colors.green('✅ Created file: src/middleware/auth.ts'));
  console.log(colors.green('✅ Created file: src/middleware/errorHandler.ts'));
  console.log(colors.green('✅ Created file: .env'));
};

// Generate TypeScript server template
const generateServerTemplate = (projectName: string): string => {
  return `import express, { Application, Request, Response, NextFunction } from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import dotenv from 'dotenv';

import { connectDB } from './config/database';
import { errorHandler } from './middleware/errorHandler';
import { setupSwagger } from './config/swagger';

// Import routes
import indexRoutes from './routes/index';
import authRoutes from './routes/auth';

dotenv.config();

const app: Application = express();
const PORT: number = parseInt(process.env.PORT || '8000');

// Connect to MongoDB
connectDB();

// Security middleware
app.use(helmet());
app.use(cors({
  origin: process.env.FRONTEND_URL || 'http://localhost:5000',
  credentials: true
}));

// Rate limiting
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100, // limit each IP to 100 requests per windowMs
  message: 'Too many requests from this IP, please try again later.'
});
app.use('/api/', limiter);

// Body parsing middleware
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));

// Setup Swagger documentation
setupSwagger(app);

// Routes
app.use('/api', indexRoutes);
app.use('/api/auth', authRoutes);

// Health check endpoint
app.get('/health', (req: Request, res: Response) => {
  res.status(200).json({ 
    status: 'OK', 
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
    environment: process.env.NODE_ENV || 'development',
    version: '1.0.0'
  });
});

// Error handling middleware (should be last)
app.use(errorHandler);

// 404 handler
app.use('*', (req: Request, res: Response) => {
  res.status(404).json({ 
    success: false, 
    message: 'Route not found',
    path: req.originalUrl
  });
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(\`🚀 Server running on port \${PORT}\`);
  console.log(\`📱 Environment: \${process.env.NODE_ENV || 'development'}\`);
  console.log(\`📚 API Documentation: http://localhost:\${PORT}/api-docs\`);
});

export default app;
`;
};

program
  .name('koti')
  .description('⚠️  DEVELOPMENT VERSION: CLI tool to generate TypeScript Bun API projects with Express and MongoDB\n    This is an initial development release and may contain errors or bugs.\n    Use at your own discretion and always review generated code before production use.')
  .version('1.0.3');

// TypeScript Model Generation Command
program
  .command('create:model')
  .argument('<model-name>', 'Name of the model to create')
  .description('Create a new TypeScript model with schema registry')
  .action(async (modelName: string) => {
    try {
      console.log(colors.blue(`🏗️ Creating TypeScript model: ${capitalize(modelName)}`));
      
      const rl = createReadlineInterface();
      const fields: { name: string; type: string; required: boolean; unique?: boolean; default?: string }[] = [];
      
      console.log(colors.cyan('\n📝 Define your model fields:'));
      console.log(colors.dim('Available types: String, Number, Date, Boolean, ObjectId, Array, Mixed'));
      console.log(colors.dim('Type "done" when finished\n'));

      let fieldName = '';
      while (fieldName !== 'done') {
        fieldName = await askQuestion(rl, colors.yellow('Field name (or "done" to finish): '));
        
        if (fieldName === 'done') break;
        if (!fieldName.trim()) continue;

        const fieldType = await askQuestion(rl, colors.yellow(`Type for ${fieldName}: `));
        const isRequired = (await askQuestion(rl, colors.yellow('Required? (y/n): '))).toLowerCase() === 'y';
        const isUnique = (await askQuestion(rl, colors.yellow('Unique? (y/n): '))).toLowerCase() === 'y';
        const defaultValue = await askQuestion(rl, colors.yellow('Default value (press enter to skip): '));

        fields.push({
          name: fieldName,
          type: fieldType,
          required: isRequired,
          unique: isUnique || undefined,
          default: defaultValue || undefined
        });

        console.log(colors.green(`✅ Added field: ${fieldName} (${fieldType})`));
      }

      rl.close();

      // Generate TypeScript model file
      const modelContent = generateTypeScriptModel(modelName, fields);
      const modelPath = path.join(process.cwd(), 'src', 'models', `${capitalize(modelName)}.ts`);
      
      await fs.ensureDir(path.dirname(modelPath));
      await fs.writeFile(modelPath, modelContent);
      
      console.log(colors.green(`✅ Created TypeScript model: src/models/${capitalize(modelName)}.ts`));
      console.log(colors.cyan('\n📚 Next steps:'));
      console.log('   • Import the model in your controllers');
      console.log('   • Update the schema registry if needed');
      console.log('   • Run TypeScript compilation: npm run build');

    } catch (error) {
      console.error(colors.red('❌ Error creating model:'), (error as Error).message);
      process.exit(1);
    }
  });

// TypeScript Enum Generation Command
program
  .command('create:enum')
  .argument('<enum-name>', 'Name of the enum to create')
  .description('Create a new TypeScript enum')
  .action(async (enumName: string) => {
    try {
      console.log(colors.blue(`📋 Creating TypeScript enum: ${capitalize(enumName)}`));
      
      const rl = createReadlineInterface();
      const enumType = await askQuestion(rl, colors.yellow('Enum type (string/number): '));
      
      if (!enumTypes.includes(enumType)) {
        console.log(colors.red('❌ Invalid enum type. Use "string" or "number"'));
        rl.close();
        return;
      }

      const values: { key: string; value: string | number }[] = [];
      
      console.log(colors.cyan('\n📝 Define your enum values:'));
      console.log(colors.dim('Type "done" when finished\n'));

      let key = '';
      while (key !== 'done') {
        key = await askQuestion(rl, colors.yellow('Enum key (or "done" to finish): '));
        
        if (key === 'done') break;
        if (!key.trim()) continue;

        let value: string | number;
        if (enumType === 'string') {
          value = await askQuestion(rl, colors.yellow(`String value for ${key}: `));
        } else {
          const numValue = await askQuestion(rl, colors.yellow(`Number value for ${key}: `));
          value = parseInt(numValue);
        }

        values.push({ key: key.toUpperCase(), value });
        console.log(colors.green(`✅ Added: ${key.toUpperCase()} = ${value}`));
      }

      rl.close();

      // Generate TypeScript enum file
      const enumContent = generateTypeScriptEnum(enumName, enumType as 'string' | 'number', values);
      const enumPath = path.join(process.cwd(), 'src', 'enums', `${capitalize(enumName)}.ts`);
      
      await fs.ensureDir(path.dirname(enumPath));
      await fs.writeFile(enumPath, enumContent);
      
      console.log(colors.green(`✅ Created TypeScript enum: src/enums/${capitalize(enumName)}.ts`));

    } catch (error) {
      console.error(colors.red('❌ Error creating enum:'), (error as Error).message);
      process.exit(1);
    }
  });

// TypeScript Controller Generation Command
program
  .command('create:controller')
  .argument('<controller-name>', 'Name of the controller to create')
  .description('Create a new TypeScript controller')
  .action(async (controllerName: string) => {
    try {
      console.log(colors.blue(`🎮 Creating TypeScript controller: ${capitalize(controllerName)}`));
      
      const controllerContent = generateTypeScriptController(controllerName);
      const controllerPath = path.join(process.cwd(), 'src', 'controllers', `${toCamelCase(controllerName)}Controller.ts`);
      
      await fs.ensureDir(path.dirname(controllerPath));
      await fs.writeFile(controllerPath, controllerContent);
      
      console.log(colors.green(`✅ Created TypeScript controller: src/controllers/${toCamelCase(controllerName)}Controller.ts`));
      
    } catch (error) {
      console.error(colors.red('❌ Error creating controller:'), (error as Error).message);
      process.exit(1);
    }
  });

// TypeScript Service Generation Command
program
  .command('create:service')
  .argument('<service-name>', 'Name of the service to create')
  .description('Create a new TypeScript service')
  .action(async (serviceName: string) => {
    try {
      console.log(colors.blue(`⚙️ Creating TypeScript service: ${capitalize(serviceName)}`));
      
      const serviceContent = generateTypeScriptService(serviceName);
      const servicePath = path.join(process.cwd(), 'src', 'services', `${toCamelCase(serviceName)}Service.ts`);
      
      await fs.ensureDir(path.dirname(servicePath));
      await fs.writeFile(servicePath, serviceContent);
      
      console.log(colors.green(`✅ Created TypeScript service: src/services/${toCamelCase(serviceName)}Service.ts`));
      
    } catch (error) {
      console.error(colors.red('❌ Error creating service:'), (error as Error).message);
      process.exit(1);
    }
  });

// TypeScript Middleware Generation Command
program
  .command('create:middleware')
  .argument('<middleware-name>', 'Name of the middleware to create')
  .description('Create a new TypeScript middleware')
  .action(async (middlewareName: string) => {
    try {
      console.log(colors.blue(`🛡️ Creating TypeScript middleware: ${toCamelCase(middlewareName)}`));
      
      const middlewareContent = generateTypeScriptMiddleware(middlewareName);
      const middlewarePath = path.join(process.cwd(), 'src', 'middleware', `${toCamelCase(middlewareName)}.ts`);
      
      await fs.ensureDir(path.dirname(middlewarePath));
      await fs.writeFile(middlewarePath, middlewareContent);
      
      console.log(colors.green(`✅ Created TypeScript middleware: src/middleware/${toCamelCase(middlewareName)}.ts`));
      
    } catch (error) {
      console.error(colors.red('❌ Error creating middleware:'), (error as Error).message);
      process.exit(1);
    }
  });

// Legacy JavaScript Model Command (for backward compatibility)
program
  .command('model')
  .argument('<model-name>', 'Name of the model to create')
  .description('Create a new model with interactive setup (legacy)')
  .action(async (modelName: string) => {
    try {
      console.log(colors.yellow('⚠️ Using legacy JavaScript model generation'));
      console.log(colors.blue(`🏗️ Creating model: ${capitalize(modelName)}`));
      
      // Legacy implementation would go here - simplified for TypeScript conversion
      console.log(colors.dim('Use "koti create:model" for TypeScript models'));
      
    } catch (error) {
      console.error(colors.red('❌ Error creating model:'), (error as Error).message);
      process.exit(1);
    }
  });

program
  .command('new')
  .alias('create')
  .argument('<project-name>', 'Name of the project to create')
  .description('Create a new TypeScript Bun API project')
  .action(async (projectName: string) => {
    try {
      console.log(colors.blue(`🚀 Creating TypeScript Bun API project: ${projectName}`));
      
      const projectPath = path.join(process.cwd(), projectName);
      console.log(colors.dim(`📁 Project directory: ${projectPath}`));
      
      // Create project directory
      await fs.ensureDir(projectPath);
      
      // Create src directory structure
      const srcPath = path.join(projectPath, 'src');
      const directories = [
        'config', 'controllers', 'middleware', 'models', 
        'routes', 'types', 'utils', 'services', 'schemas', 'enums'
      ];
      
      for (const dir of directories) {
        await fs.ensureDir(path.join(srcPath, dir));
        console.log(colors.green(`✅ Created directory: src/${dir}/`));
      }

      // Generate files from templates
      for (const [fileName, content] of Object.entries(projectTemplates)) {
        const filePath = path.join(projectPath, fileName);
        const processedContent = content.replace(/{{PROJECT_NAME}}/g, projectName);
        await fs.writeFile(filePath, processedContent);
        console.log(colors.green(`✅ Created file: ${fileName}`));
      }

      // Generate TypeScript server file
      const serverContent = generateServerTemplate(projectName);
      await fs.writeFile(path.join(srcPath, 'server.ts'), serverContent);
      console.log(colors.green('✅ Created file: src/server.ts'));

      // Copy TypeScript template files
      const templatePath = path.join(__dirname, '..', 'templates');
      const tsTemplateFiles = [
        { from: 'src/config/database.ts', to: 'src/config/database.ts' },
        { from: 'src/config/swagger.ts', to: 'src/config/swagger.ts' },
        { from: 'src/types/api.ts', to: 'src/types/api.ts' },
        { from: 'src/utils/AppError.ts', to: 'src/utils/AppError.ts' }
      ];

      for (const file of tsTemplateFiles) {
        const templateFilePath = path.join(templatePath, file.from);
        const projectFilePath = path.join(projectPath, file.to);
        
        if (await fs.pathExists(templateFilePath)) {
          await fs.ensureDir(path.dirname(projectFilePath));
          await fs.copy(templateFilePath, projectFilePath);
          console.log(colors.green(`✅ Created file: ${file.to}`));
        }
      }

      // Generate additional necessary files
      await generateEssentialFiles(projectPath, projectName);
      
      console.log(colors.green('\n🎉 TypeScript project created successfully!'));
      
      console.log(colors.cyan('\n📋 Next steps:'));
      console.log(`   1. cd ${projectName}`);
      console.log('   2. bun install');
      console.log('   3. Update .env file with your MongoDB URI and JWT secret');
      console.log('   4. Start MongoDB server');
      console.log('   5. bun run dev');
      
      console.log(colors.blue('\n📚 Useful commands:'));
      console.log('   • npm run build   - Build TypeScript to JavaScript');
      console.log('   • npm start       - Start production server');
      console.log('   • bun run dev     - Start development server with Bun');
      console.log('   • npm run dev:ts  - Start development server with ts-node');

      console.log(colors.cyan('\n🌐 Default endpoints:'));
      console.log('   • http://localhost:8000/health     - Health check');
      console.log('   • http://localhost:8000/api/       - API welcome');
      console.log('   • http://localhost:8000/api-docs   - Swagger documentation');

      console.log(colors.cyan('\n🔐 Authentication endpoints:'));
      console.log('   • POST /api/auth/register - Register user');
      console.log('   • POST /api/auth/login    - Login user');
      console.log('   • GET  /api/auth/me       - Get current user');
      
      console.log(colors.yellow('\n💡 Don\'t forget to:'));
      console.log('   • Set up your MongoDB database');
      console.log('   • Generate a secure JWT secret');
      console.log('   • Configure your environment variables');
      console.log('   • Review the generated TypeScript code');
      
      console.log(colors.red('\n⚠️  IMPORTANT DISCLAIMER:'));
      console.log('   • This is a development version (v1.0.3) and may contain errors');
      console.log('   • Review all generated code before production use');
      console.log('   • Test thoroughly in development environments');
      console.log('   • Update dependencies to latest secure versions');
      
      console.log(colors.green('\nHappy coding! 🚀'));

    } catch (error) {
      console.error(colors.red('❌ Error creating project:'), (error as Error).message);
      process.exit(1);
    }
  });

program.parse();